*---------------------------------------------------------------------*
*                                                       OBS_VAR.FTNI  *
*                                                                     *
*     LIst of variable names to accompany the include file OBS_VAR    *
*                                                                     *
*     J.L. Davis 870311                                               *
*---------------------------------------------------------------------*
  
      data list_name /'BTAPE'
     .    ,           'DATA_FLAG'
     .    ,           'DATA_AMP'
     .    ,           'ION_FLAG'
     .    ,           'NUM_CHANNELS'
     .    ,           'NUM_GRP_AMB'
     .    ,           'NUM_WVR_FRQ'
     .    ,           'MEDIUM_FLAG'
     .    ,           'PHASE_CAL'
     .    ,           'SITE'
     .    ,           'SOURCE'
     .    ,           'WVR_CODE'
     .    ,           'NUM_PHS_AMB'
     .    ,           'FRNGE_QUAL'
     .    ,           'AZIMUTH'
     .    ,           'ATM_PART'
     .    ,           'AXO_PART'
     .    ,           'AXO_CONT'
     .    ,           'CABLE_CONT'
     .    ,           'CORR_COEFF'
     .    ,           'DURATION'
     .    ,           'ELEV'
     .    ,           'ETD_CONT'
     .    ,           'ETD_PART'
     .    ,           'ETD_EXT_PART'
     .    ,           'FEED_ROT_CONT'
     .    ,           'FREQ_SEQ'
     .    ,           'GAMMA_PART'
     .    ,           'GEN_REL_CONT'
     .    ,           'ION_CORR'
     .    ,           'ION_SIGMA'
     .    ,           'NUT_PART'
     .    ,           'OCEAN_CONT'
     .    ,           'PARLX_PART'
     .    ,           'PTD_CONT'
     .    ,           'PHASE_CAL_CONT'
     .    ,           'PMU_PART'
     .    ,           'PRESSURE'
     .    ,           'REL_HUM'
     .    ,           'DB_SIGMA'
     .    ,           'SNR'
     .    ,           'SITE_PART'
     .    ,           'SOURCE_PART'
     .    ,           'SOURCE_STRUC_CONT'
     .    ,           'TEMP_C'
     .    ,           'USER_CONT'
     .    ,           'USER_DRY_ZEN'
     .    ,           'USER_WET_ZEN'
     .    ,           'WVR_AZIM'
     .    ,           'WVR_DBASE'
     .    ,           'WVR_ELEV'
     .    ,           'WVR_FRQ'
     .    ,           'WVR_TANT'
     .    ,           'WVR_TANT_SIG'
     .    ,           'GRP_AMB'
     .    ,           'OBSERVABLE'
     .    ,           'PHS_AMB'
     .    ,           'PHS_REF_FRQ'
     .    ,           'DB_THEORETICAL'
     .    ,           'THEORETICAL'
     .    ,           'SIGMA'         /
 
