# Generic Makefile for kf/glist - see documentation at libraries/comlib/Makefile.generic
# Last changed by R. King July 23, 1996

#LABELS: glist:glist:NONE:glist
#LABELS: glist_gmt:glist_gmt:NONE:glist_gmt

#SHARELIB: ../glinit:glinit_lib
#SHARELIB: ../glout:glout_lib
#SHARELIB: ../globk:globk_lib
#SHARELIB: ../Khandlers:KalObs_hndl_lib  
#SHARELIB: ../gen_util:gen_util_lib
#SHARELIB: ../../libraries/matrix:kinv_lib
#SHARELIB: ../../libraries/comlib:com_lib

