CTITLE CTOG_CMDS_BD

      block data ctog_cmds_bd

      implicit none

*     This block data sets up the commands and the other option data
*     statements for ctogobs program.

      include '../includes/kalman_param.h'
      include 'ctogobs_com.h'
 
 
      data ctog_commands /  'END',
     .                      'RNG_JUMP_TOL',
     .                      'CLK_RESET_TOL',
     .                      'RNG_RESID_TOL',
     .                      'RNG_NOISE', 
     .                      'MAX_RCLK_ITER',
     .                      'REL_CLK_WEIGHT',
     .                      'RNG_CLK_ROOT',
     .                      'PHS_CLK_ROOT',
     .                      'PHS_RES_ROOT', 
     .                      'SNG_DIFF_ROOT', 
     .                      'RESIDUAL_SITE',
     .                      'RCV_ALLAN_SD',
     .                      'REMOVE_BIAS_COND',
     .                      'USE_GAMIT_ELEV',
     .                      'USE_CVIEW_EDIT',
     .                      'IGNORE_GAPS',
     .                      'EDIT_SITE_SV',
     .                      'PHS_FIT_TOL',
     .                      'STATUS_REPORT',
     .                      'DD_REPORT',
     .                      'MIN_ELEVATION',
     .                      'TRIM_ONEWAY_TOL',
     .                      'DD_RETURN_SIZE',
     .                      'DD_FIT_TOL',
     .                      'USE_MM_RANGE',
     .                      'ALLOW_ONE_BG',
     .                      'ION_JUMP_TOL',
     .                      'SCAN_SITES',
     .                      'REMOVE_MS_JUMP',
     .                      'FLAG_GAPS',
     .                      'SUMMARY_FILE',
     .                      'REMOVE_FIRST_BIA',
     .                      'GAP_SIZE',
     .                      'MAX_SCAN_EDIT',
     .                      'NP_SET',
     .                      'SITE_PARAMS',
     .                      'APPLY_PHS_CLK',
     .                      'USE_POSTFIT',
     .                      'POSTFIT_EDIT',
     .                      'PF_REMOVE_BF',
     .                      'AZ_MASK',
     .                      'IGS_CLK_FILE',
     .                      'USE_ORIG_BF',
     .                      'MAX_CHAN',
     .                      'LC_AUTCLN',
     .                      'L1ONLY',
     .                      'PREFIT_CLK',
     .                      'APP_ION',
     .                      'REMAP_GLONASS',       
     .                      'SPARE51',       
     .                      'SPARE52',       
     .                      'SPARE53',      
     .                      'SPARE54',       
     .                      'SPARE55'       / 

      data status_rep_opts / 'CLK_JMP_PROC',
     .                       'CLK_JMP_VAL',
     .                       'BIAS_ADDED',
     .                       'PASS1_SLIPS',
     .                       'PASS2_SLIPS',
     .                       'DD_TRIALS',
     .                       'DD_ESTIMATES',
     .                       'ELEV_DIST',
     .                       'RUN_PARAMS',
     .                       'DD_SCAN',
     .                       'DD2SCAN',
     .                       'PC_BIASEST',
     .                       'PC_RMS  ',
     .                       'FDD',
     .                       'AZNAMEAN',      ! Output AZMEAN and NAMEAN to sum file
     .                       'PRESCANCLK' / 

      data edit_names /      'LSNR',
     .                       'GF03',
     .                       'RCLK',
     .                       'GF02',
     .                       'BEND',
     .                       'BCLS',
     .                       'NPED',
     .                       'NRMS',
     .                       'MULP',
     .                       'WVRB',
     .                       'METB',
     .                       'PREP',
     .                       'PRER',
     .                       'GF-1',
     .                       'GF04',
     .                       'ELSG',
     .                       'DNST',
     .                       'DNSV',
     .                       'DDSC',
     .                       'PFED',
     .                       'GFUN',
     .                       'BDL2',
     .                       'NODD',
     .                       'ELEV',
     .                       'EDIT',
     .                       'MMRG',
     .                       'ELCL',
     .                       'NU28',
     .                       'NU29',
     .                       'NODT',
     .                       'BFLA',
     .                       'BFLG'  /
 
      end
