      Subroutine convertc_help   
      write(*,*) 
      write(*,*) "CONVERTC: Converts coordinate types and files"  
      write(*,*) " "
      write(*,*) "Runstring:"
      write(*,*) " "
      write(*,*) " convertc <infile> <outfile> <outfile-type> "
      write(*,*) "      OR    "
      write(*,*) " convertc <in-coords> <out-coord-type> "    
      write(*,*) "      OR"
      write(*,*) " convertc <in-coords> <in-vels> <out-coord-type>"
      write(*,*) " " 
      write(*,*) " where "
      write(*,*) " " 
      write(*,*) " <infile> is the name of the input file."
      write(*,*) "  Type determined by convertc; supported:"
      write(*,*) "   GLOBK apr file (new GAMIT l-file), XYZ"
      write(*,*) "   GLOBK velocity file (lon/lat ENU velocity"
      write(*,*) "   GLOBK glist file (lon/lat)    "
      write(*,*) " <in-coords> X Y Z (m) or lon lat ht (deg, m)"    
      write(*,*) " <in-vels> Xdot Ydot Zdot OR Ndot Edot Udot (m/yr)"
      write(*,*) " <outfile> is the name of the output file"      
      write(*,*) " <outfile-type> is the type of output file or coords:"
      write(*,*) "   LFILE GAMIT oldstyle, spherical deg/min/sec"
      write(*,*) "   APR   GLOBK apr file (new GAMIT l-file), XYZ"
      write(*,*) "   VEL   GLOBK velocity file (lon/lat ENU velocity"
      write(*,*) "   KML   Google Earth input (lat/lon/ht)"  
      write(*,*) "   GEO   Geodetic coords (lon/lat/ht), full precision"
      write(*,*) "   GEP     for longitude 0-360  (GEO is -180 to +180)"
      write(*,*) " If coords input on command-line, output is to screen" 
      write(*,*) "    ---only XYZ, GEO, and GEP allowed as output"
      write(*,*) " "                                                 
      write(*,*) " Examples: "
      write(*,*) "  convertc emed.apr emed.kml KML  "
      write(*,*) "  convertc 918129.451 -4346071.255  4561977.839 GEO" 
      write(*,*) "  convertc  -112.567 43.36 27.2  XYZ"
      return   
      end

