      SUBROUTINE DMS(ANGLE,IDEG,MIN,SEC)
C
C     CONVERTS AN ANGLE IN RADIANS TO DMS
C
      IMPLICIT REAL*8(A-H,O-Z)
      PI=4.D0*DATAN(1.D0)
      TWOPI=2.D0*PI
C
      TANGLE=ANGLE
   20 IF(TANGLE.LT.TWOPI) GO TO 10
      TANGLE=ANGLE-TWOPI
      GO TO 20
   10 ANGDEG=TANGLE*180.D0/PI
      IDEG=IDINT(ANGDEG)
      A=DBLE(FLOAT(IDEG))
      C=ANGDEG-A
      C=C*60.D0
      MIN=IDINT(C)
      B=DBLE(FLOAT(MIN))
      D=C-B
      SEC=D*60.D0
      DSEC=SEC-60.D0
      DABSEC=DABS(DSEC)
      IF(DABSEC.GT.1.D-9) GO TO 30
      SEC=0.D0
      MIN=MIN+1
   30 CONTINUE
      IF(MIN.LT.60) GO TO 40
      MIN=MIN-60
      IDEG=IDEG+1
   40 CONTINUE
C
      RETURN
      END
