      subroutine FVERSN( vers )

      CHARACTER*10 GETMAC,MACHIN
      character*45 libver
      character*45 vers
      character*50 message

      integer ierr


      machin = getmac(1)
      write (vers,5) trim(machin)
    5 format ('10.52 of 2021/01/14 00:12 UTC (',a,')' )
      if( ierr.ne.0 ) call report_stat('WARNING','FVERSN','FIXDRV',
     .                                  vers,'IOSTAT ERR',ierr)
c     The following line contains magic SCCS keywords which will be
c     automatically updated by delta and get. This no longer used.
c    5 format ('%I% of %E% %U% (',a,')')

c Write the first message in the status file and the screen header

      message = 'Started v.'//vers
      call report_stat('STATUS','FIXDRV','fixdrv',' ',message,0)
c      write(  *, '(///,a)' ) ' GAMIT Driver Program'

c Write the library and program versions to the screen

c     get library version
      call lversn(libver)
c      WRITE(*,*) ' FIXDRV v.'//vers 
c     no longer write a print file unless recalculating clocks 
c     no longer write to the screen except for report_stat call
c      ---move this code to fixdrv.f
c      write(lprint,*) ' FIXDRV v.'//vers
c      write(*,*) ' Library v.'//libver
c      write(lprint,*) ' Library v.'//libver 
c      write(*,*) ' '
c      write(lprint,*) ' '
c
C VERSION 1.00    Left by Seiichi Shimada
C Version 1.01    Modified THDRED to
C                  (1) print warning if no orbit partials rather than
C                      stop
C                  (2) get G-file name properly when T-file
C                      generated by BCTOT
C                  Add this subroutine (FVERSN), call from FIXDRV3
c                  Yehuda Bock 12/13/90
c                  Rename FIXDRV3, FIXDRV
c                  Yehuda Bock 12/14/90
c sent to MIT
c Version 1.02     Fix MDMAKE to determine clock model correctly
c                  Remove reference to gbat in BMAKE
c                  Yehuda Bock 12/20/90
c
c Version 1.03     Change NXEPOC,IYRCHD,NXSAT,SETMRD,SMAKE to match the
c                     new C-file format
c                  Fix a bug for opening a non-existing C-file (BMAKE)
c                  Change satellite weighting format (SOMAKE)
c                  Escape from two-line file dfile.edt, using picknm directly
c                      (FIXDRV)
c                  Take the suffix of D-file in stead of T-file as the suffix
c                     of M-, V-, Q-file (FIXDRV,BMAKE)  DND 03/02/91
c                  Add reading antenna offsets from SITED. file.
c                     Changes to SMAKE, new routine RSITED --King 91/3/2
c                  Pass unit number and add library version to FVERSN
c                     Changes to FIXDRV & FVERSN -- King 91/3/2
c                  Change BMAKE to set IDATUM=0 for geocentric (temporary
c                     fix by King 91/3/8
c Version 8.1
c                  Install in SCCS at MIT  - king 91/3/15
c Version 8.2
c                  Minor printout changes in SMAKE and CLKER1
c                      king 91/3/15
c version 8.3      Put in driver/sccs directory - kurt 91/03/16
c                  SMAKEF:  change name from SMAKE, to avoid conflict with driver
c                           call CLKERA instead of CLKER1
c                  THDREDF: change name from THDREDF, to avoid conflict with driver.
c                  TAIUTC: eliminate in favor of lib routine.
c                  FIXDRV: correct some English, and use available K-file.
c                          ignore KFILE column in favor of KLOCK column.
c                  CLKER1: eliminate in favor of cubic CLKERA
c                  LFNTOP: eliminate backslash because it is not necessary under
c                          SR10.2, and because it does not compile on the sun.
c                  BMAKE:  call thdredf instead of thdred
c                          better error messages
c                          preserve series letter from X- to C-files.
c                          e.g. XaaaaB.123 will produce CaaaaB.123
c                          Yehuda's way gives           CaaaaA.123,
c                          which can cause confusion and overwrite things.
c                  SOMAKE: better error messages, match on *4* characters of
c                          site code, rather than just 3
c                  CLKERA: do cubic polynomial fit to receiver clocks.
c                  RDSEST: better error messages
c                  RDSITT: match on *4* characters of site code
c                  MDMAKE: match on *4* characters of site code
c version 8.4      minor patches: Kurt 910317
c                  MDMAKE: read KLOCK correctly
c                  READD:  do not use pickfn in batch mode, because
c                          it does not work on the sun.
c                  CEMAKE:  use unix on suns, instead of dlf command
c                  CERUN:   use unix on suns, instead of dlf command
c                  EIMAKE:  use unix on suns, instead of dlf command

c version 8.5      Scripps changes implemented in MIT version:
c                  SMAKEF: fix bug after XHDRED, LATMM => LATM
c                  MDMAKE: comment out dlf for C-files
c                  MDMAKE: modify KLOCK check (old code commented out)
c                          Y. Bock 91/04/08
c note:
c                  All sites are assumed to use J-file. If no J-file is
c                  desired place JNONE in D-file.
c                  CEMAKE: comment out dlf
c                  SOMAKE: change spelling of choise=>choice, unfortunately
c                          this also requires us to change input SESTBL
c                          Y. Bock 91/04/08
c
c                  Scripps and/or MIT changes implemented by R. King 91/04/09:
c                  FIXDRV: Change call to BMAKE to include SESTBL; add 'Normal stop'
c                  MDMAKE: Remove code to dlf in regular solution (Scripps
c                           change applied only to Apollo)
c                          Restore Kurt's KLOCK check code (KFILE column of SESTBL
c                           removed since not used--see FIXDRV 8.3 change)
c                  SOMAKE: (No change:  MIT version has both 'choice' and 'choise' for now)
c
c                  Additional changes by Kurt implemented by R. King 91/04/16:
c                  FIXDRV, BMAKE, SOMAKE: Hardwire sesstbl. and sittbl. as names but
c                          also pass them into BMAKE.  Use the same file names for all
c                          sessions, so do not open and close them multiple time.                         KAE
c                  FIXDRV: Name .bat file after D-file name, not S-file name
c                  PLOTK, CLKERA: K-file name taken from X-file name (**ignores name in
c                          column, doesn't care if column is there or not, looks for
c                          any available file alphabetically).
c                          Display clock residuals only if interactive run.
c                  MDMAKE: Add commented (ie with #) deletes for MODEL/AUTCLN sequence
c                  SMAKEF: Fix call to CHDRED.
c
c version 8.6     SOLRUN: Fix bias fixing code for L1&L2 independent mode
c                  New Makefile, cpu mathlib_sr10, maxsit=maxnet=37, maxsat=15
c                 Remove vers variable from FIXDRV & FVERSN
c                 CEMAKE: AUTCLN automatically deletes old C-files, remove dlf & rm
c                 CEMAKE: change #AUTCLN to #DBLCLN
c                 MDMAKE: Apollo users using unix commands
c                 SOMAKE: Get rid of "choise" once and for all
c                 SOMAKE: Improve debug comments
c                 FIXDRV: Check is max mumber of sessions exceeded
c                 BMAKE : Add call to DBMAKE (for DBLCLN batch file)
c                 DBMAKE: New subroutine for Shimon's new DBLCLN
c                 FIXDRV: Comment out getarg for time being
c                 Yehuda Bock 91/05/25
c                 FIXDRV: Change screen output for program name
c                         Screen output for session number moved to
c                           proper location
c                 SMAKEF: Shorten screen output when SITED-file unavailable
c                 CLKERA: Do not print out matrix singular message for segment fits
c                          (it just confuses the operator)
c                 BMAKE:  Improve SESTBL error ouput
c                         Comment out "edit information" option
c                 Yehuda Bock 91/05/26
c                 FIXDRV: Reorder opening of SITTBL & SESTBL
c                         Undid KF change to call to ORDSIT for
c                          multi-session mode
c                         Close LSITE at end of session loop
c                 ORDSIT: Fix DND English
c                 BMAKE : Reorder call to DBLCLN & add DOY argument
c                         Remove gbat
c                         Update M-file name for full solution
c                 DBLCLN: Pass day of year argument
c                 MDMAKE: Remove rm's from batch file
c                 Question: What do we do about J-file for multi-session?
c                 I recommend changing D-file format and have a
c                 J-file for each session
c                 Yehuda Bock 91/05/27
c                 CLKERA: initialize tmt0
c                 BMAKE:  Add another ARC run at end of complete solution
c                         Make DBLCLN part of quick solution (rwk special request)
c                         Remove TIME-VER option
c                         Rename C.S.FREE-RECALC option CLEANED
c                 SOMAKE: Remove TIME-VER option
c                         Rename C.S.FREE-RECALC option CLEANED
c                 Checked PREFIT option - it runs all modules before CFMRG
c                  (including DBLCLN) - good option let's keep (name ok)
c                 Checked 2-ITERATION option - works fine
c                 FIXDRV,BMAKE: Generalize J-file for multi-session
c                 DBMAKE: Query whether to trash input C-file
c                 CEMAKE: Query whether to trash input C-file
c                 MDMAKE: Query whether to trash input C-file
c                 Yehuda Bock 91/05/28
c                 Satellite channel code in SITTBL. has been already deleted
c                 CLKERA: change allen variance cutoff to 2 microseconds
c                         (if no synch output allen variance)
c                 Yehuda Bock 91/05/29
c                 FIXDRV,SMAKEF,NXEPOC,NXSAT,SETMRD,SOMAKE,BMAKE:
c                         remove PHSEDT (PHASE TYPE in SESTBL.), replace phsedt
c                          variable by XORC
c                 FIXDRV: integer the variable KLOCK
c                 PREFIT ok
c                 QUICK ok
c                 1-ITERATION ok
c                 2-ITERATION ok
c                 1-CLEANED, 2-CLEANED, 3-CLEANED ok
c                 SOMAKE, BMAKE, SOLVRN(new) : station/satellite selection
c                 Yehuda Bock 91/06/03
c                 SOMAKE: change format for satellite constraints (from SESTBL.)
c                         (this needs to be correct in SESTBL.)
c                 SOMAKE: In SITTBL., a 'D' in station fix column means ignore
c                         station - this is only an aesthetic addition, all the
c                         information comes from the D-file.
c                 Yehuda Bock 91/06/04
c
c                 Remove comment in SMAKEF and CLKERA and test in FIXDRV for
c                    quadratic clock since not used by CLKERA or CLKPRM
c                 Change SOMAKE to expect Y/N vice YES/NO for all queries (YES/NO will work
c                    OK, however)
c                 Replace CEMAKE with ACMAKE to write command-line output for each
c                    call of AUTCLN.  Changes to BMAKE and Makefile.
c                 BMAKE: Restore '1' and 'a' as M-, Q-file names for quick and regular.
c                    BMAKE.
c                 MDMAKE: Change the 'Are you sure?' question rather than using a new
c                    question ('Delete C-file?') for backward compatibility.
c                      --  king  91/07/01
c                 FIXDRV:  Allow command-line argument for D-file.  king 91/07/02
c              ** Replace all changed sccs routines by Scripps/rwk routines from
c                     test directory.  Update Makefile for Scipps syntax & new routines.
c                 ARMAKE:  Write ARC batch file in yy, day-of-yr format
c  version 8.7    MDMAKE:  Fix comment 'Delete input C-file?'
c                 ACMAKE:  Fix mistake in command-line argument, add output C-file
c                 FIXDRV:  Fix a few comments
c                 SOLVRN:  Add a blank to run line
c                 DBMAKE:  Change last query from 'yes' to '2'
c                     --   king  91/07/04
c  version 8.8    FIXDRV:  Remove feature of replacing 6th character of X- or
c                            C-files with the year number.   king  91/7/8
c  version 8.9    SMAKEF:  Major clean up to handle case without L-file.
c                          Kurt Feigl 91/07/10.
c  version 8.91   SMAKEF,CHDRED: Increased antennna heights by 1 decimal point
c                          Yehuda Bock & Keith Stark 91/07/10
c                 Modify comments in RSITED for antenna height variables
c                 Add comments in FIXDRV for RSITED
c                 BMAKE:   Update S-file name for 2nd quick solution
c                           for 2-ITERATION option (** not fixed properly, yet)
c                          Yehuda Bock 91/07/11
c                 ACMAKE:  Output sincln to B-file
c                          Yehuda Bock 91/07/12
c                 BMAKE:   Update S-file name for final solution
c                 DBMAKE:  In DBLCLN batch file remove day of year query
c                          Yehuda Bock 91/07/17
c                 RCMAKE:  New routine to run scanrms at very end
c                 BMAKE:   Call new RCMAKE
c                          Yehuda Bock 91/07/18
c                 BMAKE:   Do not update S-file name for cleaned data options
c                          Yehuda Bock 91/07/20
c                 SOMAKE, SOLVRN:  Change format of rad parameters to f7.2
c                          Yehuda Bock 91/07/24
c  version 8.92   SOMAKE, SOLVRN  Include pdeudorange priority option (LOBS=7)
c                          Yehuda Bock 91/08/21
c                 SMAKEF:  Add another significant place in height (0.1 mm)
c                          Yehuda Bock 91/08/25
c                 BMAKE:   Modify first input parameter to SETMRD, array
c                          element, not entire array
c                 SOLVRN:  Compute number of parameters correctly for multi-session
c                          Allow for L2-only option
c                 SOMAKE:  Bug
c                 BMAKE,CMMAKE: Output complete satellite list to CFMRG batch file
c                          Yehuda Bock 91/09/29
c                 Kinematic code changes:
c                 BMAKE,CMMAKE,MDMAKE,SOLVRN,SOMAKE,THDREDF
c                          Yehuda Bock 91/10/16
c  version 8.93   SCMAKE:  Replace SCANRMS by SCANDD
c                          Yehuda Bock 91/11/16
c  version 8.94   BMAKE:   Move after quick solution arc after dbmake
c                          Move last arc after scmake
c                          Yehuda Bock 91/11/24
c  version 8.95   NGMAKE:  Make batch file for call to TTONGS (called from BMAKE)
c                          New keywords in sestbl. (orbit id, orbit organization)
c                          Yehuda Bock 91/12/01
c                 BMAKE:   Add Export Orbit option question
c                 ARMAKE:  Expand integration period for Export Orbits
c                 TIMEUP:  New time subroutine, called by ARMAKE
c                          Yehuda Bock 91/12/26
c                 (THDREDF, BMAKE : Add LEXP = 4 option for kinematics)
c                 Update Makefile for two new subroutines.
c  version 8.13   Incorporate Scripps changes v8.91-8.95 plus the following to
c                          eliminate the S-file:
c                 FIXDRV:  Write an I-file header and call IMAKEF viz SMAKEF
c                 IMAKEF:  New routine to write the I-file station records
c                 Makefile: Add IMAKEF, remove SMAKEF, UT1RED, UT1TID, POLRED
c                                              FUNARG, FUNCOF, NUTTAT
c                 BMAKE :  Change S-file references to I-file; don't update I-file name
c                 MDMAKE:  Change S-file references to I-file
c                 TIMEUP:  Scripps fix to leap-year problem.
c                 FIXDRV:  Don't say 'Normal stop' if errors.
c                          Set ARC run by T- or G-file in D-file.   King 92/1/27
c                 Fix minor bug in CLKERA (King 91/11/7, delta'ed 92/2/8)
c version 8.14    Incoporate Scripps changes  (92/2/10)
c                 DBMAKE,BMAKE : pass MSESSN from BMAKE to DBMAKE for multi-session case
c                  (this change was missed by MIT)
c                          Yehuda Bock 92/01/08
c                 FIXDRV:  Two Fortran bugs in FIXDRV (how did this get past MIT?)
c                          Modify comment line referring to S-file
c                          Create L-file name from D-file, pass to BMAKE
c                          (default name lfile. is discontinued)
c                 BMAKE :  Call DBLCLN only once on 2-ITERATION option
c                          (this change was missed by MIT)
c                          Remove version number from BMAKE (not a bad idea but
c                           difficult to maintain)
c                          Update new L-file in BMAKE before quick & full solution
c                          Add lfile to call to SOMAKE
c                 SOMAKE : Pass lfile and ifile to SOLVRN
c                 SOLVRN : Modify to update lfile/ifile instead of s-file
c                          Yehuda Bock 2/2/92
c version 8.15    SOMAKE : Bug in warning message; explicitly type 8 variables.
c                 SOLVRN : Remove S-file references; explicitly type variables
c                 SCMAKE :  Missed previous SIO change:  Replace SCANRMS by SCANDD-YB 91/11/16
c                 IMAKEF : Get day of year from X- or C-file header,
c                           not from name of file (call DAYNUM)
c                          Yehuda Bock 2/15/92
c                 BMAKE  : Update l-file name again for two-iteration solution
c                          Yehuda Bock 2/16/92
c                 MDMAKE : Change old-style flag to 'O' vice 'X'.   King 92/2/26
c                 SOLVRN : Added input for decision-function controls.  King 92/2/26
c                 FIXDRV : Display warning about source of antenna offsets.  King 92/3/24
c                 SOLVRN : Allow station constraints in baseline mode.   King 92/3/24
c version 8.16    BMAKE  : Add SKD to XHDRED call.    King 92/3/28
c                 IMAKEF : Add SKD to XHDRED call.    King 92/3/31
c                 SOLVRN : Don't do a loose solution if 'quick'.   King 92/4/7
c                 FIXDRV, BMAKE, IMAKEF: Clean up and read session.info to check X- or C-file
c                          information or avoid need to read X- or C-file.
c                          New routines SESCHK, RSESFO, and XFORMT; remove IYRCHD and IYRXHD.
c                          Change Makefile.  King 92/4/9
c                 MDMAKE : Add C-file to call list and remove name update from routine.
c                          Fix sample file (comments only).  King 92/4/9
c                 CHDRED, IMAKEF : Fix bug in CHDRED calling sequence.   King 92/4/9
c                 SETMRD, NXEPOC, NXSAT  : Fix bug in declaration of SITNAM.  King 92/4/9
c                 BMAKE, DBMAKE : Increment C-file name for DBLCLN run.   King 92/4/23
c                 NXEPOC, SETMRD : Correct declaration of rcvrsw for CHDRED call.
c                 NEXTT1 : Replace function LEAP with library LEAPYR.
c                 Makefile: Remove EIMAKE, LEAP, and SPANUP (not used)
c                 Declare variables explicitly:  ACMAKE, CHRNUM, CLKPRM, CMMAKE, GETMD,
c                         NEXTT1, NXSAT, ORDSIT, SETMRD, SOMAKE, UPCHR, UPNAM2.  King 920423
c                 New C-file header format:  Calls to library READC2 in CHDRED and
c                         SESCHK (but do not pass out)   King 920423
c     `           Eliminate unused variables:  ACMAKE, BMAKE, DBMAKE, FIXDRV, IMAKEF
c                         MDMAKE, NXEPOC, SETMRD, SOMAKE, THDREDF, CHDRED
c                         SESCHK, SOLVRN, SCMAKE.    King 920424
c                 BMAKE, SOMAKE, IMAKEF, SETMRD:  Read RSESFO to get no. SVs if no X-file;
c                          Add error check when X-file not available.   King 920425
c                 SESCHK : Fix bug in calling RSESFO.    King 920425
c                 ORDSIT : Fix dimensions of site-name array..
c                 FIXDRV : Initialize MNET for multi-session.   King 920427
c                 SOMAKE, SOLVRN : Dimension STATCV MAXNET, not MAXSIT.  King 920428
c                 Makefile:  Remove RSESFO (moved to library).  King 920429
c                 Add session number to X- and C-file; changes to CHDRED, SESCHK,
c                         IMAKEF, XFORMT, NXEPOC, NXSAT, PLOTK, SETMRD.   King 920429
c version 9.1     Update version number and copy changes to SIO.  King/Bock 920503.
c version 9.11    SESCHK:  Fix bug in reading SAT line.   King/Liu 920505
c                 SESCHK: Continue to fix bug reading SAT line.
c                         Read year & dayoyr from X-file, convert to GPS year and dayoyr
c                         Bock 920507
c                 FIXDRV, BMAKE : Compute doy variable and pass to BMAKE
c                         Bock 920511
c version 9.12    SOLVRN: Fix questions for L- and I-files duplicate questions
c                         for SOLVE option (LOBS) 2.  Dong 920519
c                 SOLVRN: Do not output station constraint question
c                         for baseline estimation Bock 920525
c                 SESCHK: Add 1 second to UTC to GPST conversion to account
c                         for crazy TI epochs,
c                         Add stop statement at two hard stops
c                         Bock 920603
c version 9.13    SOLVRN: Restore station constraint question for baseline
c                         estimation (but fixed SOLVE).
c                 SESCHK: Explicitly type variables.
c                 FIXDRV: Read L-file name from D-file.
c                 BMAKE : Use non-updated C-file name for 3-CLEAN input.
c                         King 920604
c version 9.14    BMAKE : Clean up clean/non-clean logic as way of fixing bug in
c                         setting input C-file for 1-CLEAN or 2-CLEAN option.
c                 IMAKEF, CLKERA, CLKPRM : Fix bug in computing I-file time in
c                         C-file-input mode.   King 920606
c version 9.15    FIXDRV, SESCHK: Read station.info and call HISUB to catch problems
c                         before MODEL.    King 920611
c version 9.16    SOLVRN, SOMAKE: Allow loose GLOBK solution
c                         for BASELINE solution.
c                         Allow free-format sat constraints in sestbl.
c                         Feigl 920627 / King 920706
c version 9.17    FIXDRV  Fix bug in getting year from D-file name.
c                 SESCHK  Fix bug in setting session number if no X or C file.
c                           King 92/7/14
c version 9.18    SOLVRN  Change constraint-write for option 2 or 3.  Bock/King
c                 FIXDRV, BMAKE, SESCHK, SOMAKE, XFORMT   Refine and expand calculation of
c                         year and day-of-year for batch files and consistency checks.
c                 RDSEST, ARMAKE, BMAKE, NGMAKE, SOMAKE :   Add variable to allow missing
c                         sestbl. entries.
c                 BMAKE, SOLVRN :   Add 'Update T/L files' to sestbl.; control T/L updates in BMAKE.
c                 BMAKE, ACMAKE, DBMAKE, MDMAKE, SOMAKE :   Add optional delete commands
c                         for input C-files to sestbl.
c                 ARMAKE, BMAKE, SATNMR, XFORMT; new TGSATS, XCSATS;
c                         Rename XFORMT==>XCHECK; Makefile : Get SVs from X- or C-file
c                         for consistency.   King 920914
c                 SOMAKE  Add trap for zero a priori SV or site sigmas.
c                 CLKERA, Makefile:  Increase number of jumps allowed; move routine to /lib
c                 BMAKE:  Add 'No ARC' option to skip final integration.  King 920921
c                 BMAKE:  Remove option to read geodetic datum (not supported by L-file or
c                         Q-file.   King 920925
c                 Remove unused variables: BMAKE, DBMAKE, FIXDRV, TGSATS, XCHECK.  King 920925
c version 9.19    ACMAKE: Fix optional command to delete input C-file.  King 920930
c                 CMMAKE: Remove debug.
c                 DBMAKE: Correct option to delete C-files.  King 920930
c                 BMAKE, CMMAKE: Remove debug.  King 920930
c                 BMAKE, ARMAKE: Add warning and stop if no valid T-file epoch.  King 920930
c                 SOMAKE: Correct bug with bad batch file when no X-files.   King 921001
c                 FIXDRV, BMAKE: Remove G/T logic for integration in favor of explicit
c                         controls in BMAKE.   Bock/King  921005
c version 9.20    SOLVRN: Do not output clock file header when no clocks adjusted
c                           Bock 921108
c                 FIXDRV: Correct sittbl. open-error message.  King 921110
c                         Bock 921108
c                 SOLVRN: Add bias fixing parameters in b-file output
c                         Bock 921111
c version 9.21    BMAKE, ARMAKE: Allow initial integration w/o partials in baseline
c                         or kinematic mode.    King 921118
c                 SESCHK: Correct message for mismatched scenarios.  King 921119
c                 BMAKE:  Make the 6th character of the C-file output from MODEL in
c                         the CLEAN case the same as the 6th character of the X-file,
c                         in order to accommodate multi-session naming schemes.  Morgan/King 921203
c version 9.22    SESCHK: Fill cdoy variable properly.  Bock 920113
c                 SESCHK: Remove unused variables.  King 920114
c version 9.23    SOLVRN: Add bias searching ratio & fix old bug. Bock 930121
c version 9.24    FIXDRV: Add dhpab to HISUB call.
c                 IMAKEF, XCHECK, XCSATS: Add antcod to XHDRED call.
c                 Remove unused SMAKEF from MIT Sun directories.
c                 Remove unused SETCLK from MIT Sun and Apollo directories.
c                           King 930212
c                 SOMAKE, SOLVRN, RDSEST : Add ambiguity resolution parameters
c                        with current defaults (0.4  0.4  1000.  3.0) King 930219
c                 RDSEST : Fix bug when amibiguity parameters missing.
c                 SOMAKE:  Make defaults as stated above .   King 930223
c                 Makefile (Sun stdrel only):  add include dependence for SATNMR.
c                 BMAKE:  File update / first_arc logic for new RDSEST.
c                          King 930223 / King 930225
c version 9.25    SOMAKE, SOLVRN : Allow override of suppression of contrained-solution
c                          in H-file.    King 930319
c                 SOMAKE: Make bias-fixing defaults more conservative
c                          (old: 0.4, 0.4, 1000., 3.; new: 0.15, 0.15, 1000. 10.)
c                          Defaults also changed in SOLVE.  King 930319
c version 9.26    NGMAKE: Output batch file for new TTONGS (uses SP1 and SP3 formats)
c                 Note: SESTBL. format has changed for new TTONGS
c                 FVERSN: Problem with nblen(machine) so remove
c                 Bock/Fang 930406
c version 9.27    SITTBL: Add NZEN column - number of zenith delay parameters
c                 MDMAKE: Use NZEN parameter, output to model batch files
c                 CMMAKE: Output to cfmrg batch file number of zenith
c                         delay parameters per site
c                 BMAKE: Add variable LSITE to call to CMMAKE
c                 SOMAKE, SOLVRN: Generalize SOLVE batch file for
c                        multiple zenith delay parameters
c                        Bock 930407
c version 9.28    SESCHK: Fix bug in type of 'sec1', causing hangup in call to
c                        TIMCON.  Oral/King 930412
c version 9.29    ORDSIT: Eliminate from Makefile after copying to LIB
c                        Bock/Fang 930419
c version 9.30    FIXDRV: Check for proper D-file format.  King 930416
c version 9.31    Remove obsolete CERUN, CEMAKE, MRGRUN.
c (MIT 0715-0727) SOLVRN: Remove obsolete IAGAIN test.
c                 New SOLVE batch file:  SOMAKE, new SOLVE_RUN
c                        King 930715
c                 NSNPRN: Remove subroutine from MIT stdrel, active, and Apollo.
c                        (In /lib, and not in fixdrv/Makefile for some time).  King 930720
c                 CMMAKE, SOMAKE : Allow Zenith-delay parameter number to be missing from
c                        sittbl.   King 930715
c                 SOLVE_RUN: Fix bugs.    King 930727
c                 SOMAKE: Allow missing no. of zenith-delay parameters in sittbl.
c                        King 930727
c                 SOLVRN: Zero out half of bias 1/0 array for L1-only or L2-only.  King 930728
c version 9.31    SOLVRN: Fix SOLVE menu for multiple zenith delay
c (SIO 0723)              parameters.
c                 SOMAKE: Check if max. no. of zenith delay parameters exceeded
c                 sittbl.: Add constraints for zenith delay parameters
c                          I've allowed one constraint per site for th
c                          time being
c                 MDMAKE: Undo zenith delay output for model
c                 CMMAKE: Check if atmospheric parameters are set
c                 BMAKE:  Add variables in call to CMMAKE
c                 SOMAKE,SOLVRN: Zenith delay constraints
c                 Bock 930723
c                 SESCHK: Change jfiln variable to character*16 to match readc2
c version 9.32    UTC2GPS Add subroutine UTC2GPS (called by SESCHK) to fix over the day
c (SIO 0723-0807)          boundary problem, add to Makefile
c                         Fang/Bock 930723
c                 CMMAKE,SOLVRN, SOMAKE: Hard wire zenith delay output
c                         Bock 930804
c                 ACMAKE, DBMAKE, SCMAKE, RSITED: Remove % from include statement
c                         Bock 930807
c version 9.33    Merge MIT and SIO changes.    King 930818
c                 SOLVRN: SIO version except remove obsolete IAGAIN test.
c                        (1/0 array for L1-only, L2-only?)
c                 CMMAKE: SIO version except allow no zenith-delay parameters in sittbl.
c                 SOMAKE: SIO zenith-delay code except allow no zenith-delay parameters in
c                         sittbl.; MIT code for new batch file; remove IAGAIN.
c                 MDMAKE: Revert to orginal MIT version (no zenith delay).
c                 ACMAKE, BMAKE, DBMAKE, RSITED, SCMAKE, SESCHK, UTC2GPS, SIO version
c                 SOLVE_RUN: new MIT subroutine; add zenith-delay constraints.
c                 Makefile: Add SIO UTC2GPS and MIT SOLVE_RUN.
c                 Merge additional SIO changes (King 930823):
c                 BMAKE, ACMAKE, CGMAKE (new): CTOGOBS command line
c                                              Replace dblcln by scandd
c                 Makefile: add CGMAKE
c                 BMAKE: Remove char1 variable (unused)
c                         Bock 930822
c                 SOLVRN: Zenith-delay a prioris loose as well as tight solutions,
c                         but not autmatically for either.  King 930825
c                 MIT stdrel: copy ORDSIT to /lib and remove from directory and Makefile
c                         (930419 change missed). King 930826
c                 SESCHK:  Remove unused variables.   King 930826
c                 SOLVE_RUN:  Fix session loop; remove unused variables.   King 930826
c                 SOLVRN: Set zenith-delay a.p. for loose solution = 1 m.  King 930830
c                 SOMAKE, SOLVE_RUN: Pass name of secondary B-file.        King 930908
c                 SOLVE_RUN: Move 'Number Zen' to constraint group and allow its
c                       input from sestbl.    King 930914
c                 SOLVE_RUN: Move narrow-lane parameters to global controls and
c                       eliminate 'switch running mode'.   King 930922
c                 Allow optional entries in sittbl. (for multiple zenith-delays and
c                       antenna phase center variations.  Changes to CMMAKE, FIXDRV,
c                       MDMAKE, SOLVE_RUN, SOMAKE.   King 930922
c                 MDMAKE : write antenna-phase center model to B-file.
c                       (Remove unused MODRUN from MIT directories. ) King 930922
c                 ARMAKE : write radiation-pressure model to B-file.  King 930923
c                 RDSITT, CMMAKE, MDMAKE: Fix bug when table parameter missing.  King 930924
c                 SOLVE_RUN: Fix keyword for L1L2_INDEPENDENT, input zenith model.  King 930928
c                 SOLVE_RUN, CMMAKE, RDSITT: Fix bug if entry not found.   King 930929.
c                 SOLVRN, SOLVE_RUN: Fix bug in setting biases for L2-only.  King 930930
c                 SOLVE_RUN: Allow 'LC' for 'LC_ONLY' option.  King 930930
c                 SOLVE_RUN: Fix 'quick' and 'orbit' parameters.   King 931001.
c                 MDMAKE: Add option for earth/ocean tides.    King 931005
c                 CMMAKE: Fix bug for reading zenith-delay number.  King 931008
c                 Consolidate options for AUTCLN/SINCLN.  Remove CGMAKE. Modify
c                    Makefile, BMAKE, ACMAKE.    King 931008
c                 SOLVE_RUN: Fix output format for zenith delay model.   King 931012
c                 CMMAKE: Fix bug for reading zenith-delay number. King 931012
c                 SOMAKE: Use uppercase in sestbl. for SOLVE batch file . King 931012
c                 SOMAKE, SOLVE_RUN: Fix omission of tight orbital constraints.   King 931013
c                 XCHECK: Convert year from X-file to two digits.   King 931013
c                 BMAKE:  Check 'Delete AUTCLN' as well as 'Delete SINCLN'.   King 931015
c                 RDSEST: Blank returned string after first token to allow long
c                         autcln.cmd filename but avoid picking up comments.  King 93
c                 SESCHK: Increase formats to 32 satellites.  King 931018
c                 Remove unused variables:  TIMEUP.   King 931018
c                 SESCHK: Issue only a warning if session not found.  King 931019
c                 BMAKE : Make arc/model/autcln order different from dblcln/arc/model.
c                            King 931021
c                 SOLVE_RUN: Make piecewise linear the multi-zen default.  King 931021
c version 9.34    SOLVE_RUN: Set zen defaults correctly if no entry.  King 931214
c                 MDMAKE:  Add control for short-period pole, UT1 values.  King 931217
c                 SOLVE_RUN: Allow implicit biases for non-quick solution--but note
c                       that SOLVE can produce only a tightly constrained H-file from an
c                       implicit-biases  solution.   King 931217
c                 SOLVE_RUN: Fix bug in reading zenith-delay constraints from sittbl.;
c                       make loose-solution zenith-delay constraints the same as tight since
c                       GLOBK does not estimate zenith delays.    King 931231
c                 SOLVE_RUN: Fix bug in not adjusting radiation-pressure parameters when
c                       a priori constraints input.   King 931231
c version 9.35    SCMAKE: Comment out call to scandd.  Bock/Fang 940103
c                 SESCHK: Fix problems & correct comment line.  Bock 940104
c                 ACMAKE: Modify autcln command line to have output file.  Bock 940104
c                 SESTBL: Add iteration option on xfiles or cfiles.  Bock 940105
c                 BMAKE:  Incorporate iteration option.
c                         Make the GAMIT batch file a UNIX shell script-
c                         check that quick solution has an rms less than 5,
c                         otherwise stop processing. Bock/Fang 940105
c                 BMAKE:  Set default iteration option if no sestbl. entry.  King 940107
c                 ACMAKE: Lowercase input and output extensions.  Bock/Fang 940112
c                 ARMAKE: Add tabular interval and stepsize control for ARC.  King 940113
c                 ACMAKE: Screen output that AUTCLN is running.  Bock/Fang 940122
c                 SOLVE_RUN: Explicitly define LC_HELP & LC_RANGE options.  Bock 940201
c                 MDMAKE: Fix bug in reading Earth Rotation entry.  King 940124/940207
c                 ARMAKE: Change default integration stepsize to 75 seconds. King 940207
c                 SOMAKE: Change default to new batch file.  King 940207
c version 9.36    BMAKE:  For 3-CLEAN option: allow X-files in D-file; fix bug in getting
c                            yr,doy .  King 940210
c                 BMAKE:  Fix reading and setting of default 'clean_opt'.   King 940215
c                 VINV2:  Declare variables explicitly.  King 940215
c                 BMAKE:  Fix iteration file assignment with SINCLN option.  King 940215
c                 ACMAKE: Fix writing of place-holder with no autcln.cmd file.  King 940215
c                 MDMAKE: Read W-file name correctly from SITTBL.  Shimada/Bock 940221
c version 9.37    SOLVE_RUN: Reinstate L1,L2_INDEPEND. option,
c                            Explicitly define L1_ONLY, L2_ONLY options.  Bock/Genrich 940407
c                 BMAKE, SCMAKE: Add sestbl. control for SCANDD runs.  King 940406
c                 SOLVE_RUN: Add comment in batch file for orbit units.  King 940419
c                 SOLVE_RUN: Expand character variable to avoid abort with long sestbl.
c                        orbital a priori constraints.   King 940428
c                 Makefile: Change HP compiler switch from +E1 + e to +U77.   Fang/King 940503
c                 SOLVE_RUN: Remove unused keywords for satellite clocks.   King 940503
c                 SOLVE_RUN: Fix bug in L1,L2 options.  Bock/King  940505
c                 SOLVE_RUN: Fix quick solution when L1&L2.  Bock 940506
c                 SOLVE_RUN: Change keyword for estimating wobble.  King  940510
c version 9.39    FIXDRV, XCHECK: Add calling argument for library RSTNFO.  King 940511
c                 SOLVE_RUN: Add comment about earth-rotation units.  King 940512
c                 SOLVE_RUN: Fix MIT typo in implementing SIO change.  King 940513
c                 SOLVE_RUN: Fix messages about excluding sites/satellites.   King 940516
c                 FIXDRV: Add isod variable to rstnfo subroutine call.  Bock/Fang 940602
c verson 9.40     FIXDRV: Change comment.   King 940609
c                 Renamed SOLVE_RUN to SOMAKE, removing the old SOMAKE and SOLVRN.
c                 Makefile: Remove GETMD, SOMAKE, SOLVRN, SETMRD.   King 940609
c                 Removed obsolete BFUP, CGMAKE, CHANNL, CHECK, CONVRT, DUMPT, DRIVER,
c                    EIMAKE, ELVCUT, EPOCHS, ERRMSG, FTBLED, FUNARG, FUNCOF, DAYNUM, GETDYR,
c                    GETG, GETMD, GETUSR, EXPMNT, FJLDAY, IBMSUB, INVOKE, ION, IYRCHD, IYRXHD,
c                    JULDAY, LEAP, LNKFIL, MERROR, MONDAY, NEWFIL, NUTTAT, PDATUM, POLRED, SATCN,
c                    SCOPY, SETMRD, SINDIV, SOLRUN, SPANUP, STATCN, UT1TID, UT1RED,
c                    WTHINF from directories.   King 940609
c                 ARMAKE: Allow IGS92 constants for integration.  King 940610
c version 9.41    SOMAKE: Read zenith-delay variation parameters from sestbl. and sittbl. King 940615
c                 MDMAKE: Make wfile entry in sittbl. optional.  King 940622
c                 Makefile: Shift ranlib to be executed only once.  Herring/King 940622
c                 FIXDRV,FVERSN: correct fixdrv version number in i-file.  Bock 940625
c                 SOMAKE: Change defaults for zenith constraints to 0.5, 0.02.  King 940705
c version 9.42    SESCHK, Makefile:  Remove separate UTC2GPS to be part of SESCHK for now,
c                    with name UTC2GPSF to avoid conflict with /lib UTC2GPS.  King 940713
c                 TGSATS, XCSATS: Changes to convert FIXDRV to GPST.   King 940713/940722
c                 SESCHK: Don't convert session.info to UTC.   King 940728
c                 FIXDRV, IMAKEF: Write I-file in GPST.  King 940728
c                 SOMAKE: Don't write out G-file line; created in SOLVE.  King 940803
c                 TIMEUP: Fix problem at day boundaries.  King 940803
c                 ARMAKE: Use GPST as time argument.  King 940803
c                 SESCHK: Fix comparison of scenarios; remove attached sb gps2utc.  King 940805
c                 BMAKE: Correct rms checks for SOLVE run. Bock/Fang 940810
c                 BMAKE: Option to run job and output to null device.  Bock 940810
c                 BMAKE: Add '0-ITE' option for good-model AUTCLN runs.  King 940811
c                 BMAKE: Option to edit AUTCLN command file.  Bock 940811
c                 BMAKE: Correct rms check for full solution.  Bock/Fang 940812
c                 IMAKEF: Fix bug in idint statement.  Bock/Fang 940812
c                 BMAKE: Minor bug in running instructions at end.  King 940812
c                 SOMAKE: Set zenith-delay number and constraints even if fixing.  King 940817
c                 SESCHK: Remove comment.  King 940817
c                 IMAKEF: Fix bug in getting day.  King 940913
c version 9.43    FIXDRV, MDMAKE: Allow non-use of I-file except when KCLOCK=2.   King 940916
c                 SOMAKE: Allow more decimal places in UT1/pole constraints.    King 940927
c                 MDMAKE: Fix bug in checking I-file vs clock model.  King 940928
c                 MDMAKE, SOMAKE: Warnings for contradictory input.  King 941026
c version 9.44    MDMAKE: Antmod warnings only if they are different.  King 941105
c version 9.45    SOMAKE: Add input for pseudorange ambiguity resolution.  King 941117
c version 9.46    TGSATS: Add rad parameter names to THDRED call, increase print format.
c                          King 950104
c                 SOMAKE: Get epoch selection for SOLVE from sestbl. rather than sittbl. King 950119
c                 SOMAKE: Set tight UT1 default constraint to 1 cm.  King 950120
c                 ARMAKE: Make reference system input optional.  King 950120
c                 BMAKE:  Add sestbl. command to uncompress/compress X-files.  King 950120
c                 BMAKE:  Add sestbl. command to run CTOX; fix rms message to check only
c                           current q-file.   King 950126
c                 SOMAKE, CMMAKE: Make reading of number of zenith delays from sestb. less
c                           sensitive to extra spaces.  King 950126
c version 9.47    BMAKE:  Add iteration on clean data options (new entry to sestbl.)
c                         Fix QUICK option
c                 ACMAKE: Clean up PREFIT option
c                          Bock 950210
c                 BMAKE:  Merge MIT changes 950120-950126 with SIO changes 950210.  King 950214
c                 BMAKE:  Fix a few more bugs in iteration options.  King 950217
c version 9.48    BMAKE:  Add warning if 1-CLEAN but Initial ARC = NO.  King 950328
c                 MDMAKE: Add y-file for SV yaw model.  King 950328
c                 BMAKE:  Add 'SOLVE-only' option to replace 3-CLEAN eventually.  King 950328
c                 BMAKE:  For rms tests in script, construct q-file name from d-file in order
c                          to avoid searching leftover q-files.  King 950403
c version 9.49    TGSATS: Add model arguments to call of library THDRED.  King 950421
c version 9.50    ARMAKE, sestbl. : Allow choice of B1950 or J2000 frames for ARC.  King 950426
c                 ARMAKE: Add precession system (IAU76) to batch file if inertial system is
c                          J2000. (Not written but assumed to be IAU68 for 1950.0).  King 950509
c                 TGSATS: Add frame argument to call of library THDRED.  King 950511
c                 ARMAKE: Adjust by one column frame and precession words.  King 950511
c                 TGSATS: Add argument to THDRED call.   King 950517
c version 9.51    New C-file format:  CHDRED, SESCHK.  King 950525
c                 ARMAKE, BMAKE, TGSATS, SOMAKE, sestbl.: Allow 3 or 9 non-gravitational parameters.
c                           King 950608
c                 SOMAKE: Allow single-line sestbl. input for satellite constraints.  King 9506014
c                 SOMAKE, sestbl.:  Add input variable for maximum length of baseline for
c                           ambiguity resolution.  Bock 950604
c                 BMAKE:  Do not necessarily update L-file if 'RAW' option is set.  Bock 950617
c                 SOMAKE: Set default for maximum length for bias-fixing at 500 km.
c                           King/Bock  950620
c                 RDSEST: Refine search to identify the semi-colons before comments.  King 950622
c                 SOMAKE: Print warning and set default if bias-fixing maximum length missing
c                           from sestbl.  King 950622
c version 9.52    CHDRED, IMAKEF, NXEPOC, NXSAT, SESCHK, XCSATS:  Add offset of antenna reference
c                           point to C-file format.  King 950717
c version 9.53    ARMAKE, BMAKE, NGMAKE, SOMAKE: Need 'status' in open statement for DEC.
c                           Sanli/King  950719
c                 IMAKEF: Add logic to test for MiniMac (replace code using 'klock', which
c                           is not known yet).  Sanli/King 950719
c                 TGSATS: Remove extraneous comma in format; make header-dump commented debug
c                           instead parameter-controlled (DEC compiler recognized the unreachable
c                           statement).  Sanli/King 950719
c                 CHDRED, SESCHK: Change names of itide/iut1pol => ietide/isptide
c                           to match rest of GAMIT.  King 950720
c                 FIXDRV: fixed bug in call to imakef Fang/Tregoning 950722
c version 9.54    ARMAKE: Add message that need T-file or at least one X-file to get
c                           the integration span for ARC; could use session.info, but more
c                           logic required.  Herring/King 950724
c                 BMAKE:  For full solution, run SCANDD before exiting for too-high nrms.  Herring/King 950724
c                 MDMAKE: Don't print warning for antenna model mismatch if not listed in sestbl.
c                           Herring/King 950724
c                 FIXDRV: Read old I-file to check for all stations present (avoids learning only at
c                           the MODEL stage; make I-file checking immune to blanks at end of I-file
c                           name on the D-file.   Herring/King 950725
c                 Allow FIXDRV to work with a larger number of sites than other modules in order to
c                           run MODEL and AUTCLN with a network subdivided for SOLVE.  Add fixdrv.fti;
c                           changes to Makefile, ACMAKE, BMAKE, FIXDRV, CMMAKE, SOMAKE.  King 950726
c                 BMAKE:  Correct typo leading to misnamed output C-file in case of input C-file with
c                           0-ITER and clean data.  Herring/King 950727
c                 FIXDRV: Allow lowercase 'none' for I-file name.   King 950727
c                 NGMAKE: Correct spelling of 'unknown'in file open. Sanli/King 950728
c                 FIXDRV: Make missing station on I-file a warning only.  King 950729
c                 SOMAKE: Stop if SV constraint list in sestbl. has too few values.  King 950729
c                 BMAKE, SCMAKE: Add option for SCANDD only if bad nrms.  King 950729/950731
c                 BMAKE: Give x-file span priority over existing t-file to avoid ever-increasing
c                          arc lengths.  McClusky/King 950801
c                 BMAKE: Change default clean option to AUTCLN.  King 950802
c                 SOMAKE: Make (spatial tropospheric constraint optional. King 950803
c version 9.55    FIXDRV, SESCHK: Fix bug with setting year when x-file missing.  King 950812
c                 SOMAKE: Minor cleanup of warning message.  King 950812
c                 BMAKE:  Print out all missing SVs before stopping.  King 950812
c                 IMAKEF: Fix logic to avoid two clock fits, add missing UTC to GPST conversion
c                         (change actually in lib/clkera, not imakef), and remove redundant code.   King 950814
c                 BMAKE: Fix spelling of 'scandd'.  Herring/King 950822
c                 SOMAKE: Add comment line on SV a priori units.  King 950823
c                 BMAKE, SOMAKE: Quick solution ihfile changes.
c                 FIXDRV, BMAKE, SOMAKE: Add 'Processing Agency' to sestbl. and pass to SOLVE.
c                        Bock 950825
c version 9.56    SOMAKE:  Add entries for measurment error model with non-uniform station/SV
c                        weighting and SOLVE elevation cutoff.  King 950904
c                 SOMAKE:  Add entries for decimation factor; modify entries for measurement
c                        error model.   King 950909
c version 9.57    ARMAKE: Make default frame J2000.  King 950923
c version 9.58    ARMAKE: No, make it B1950 to protect users of old data.  King 950925
c version 9.59    MDMAKE: Remove elevation-angle entry in batch file.   King 951002
c                 Makefile: Remove SESTBL to library.  King 951003
c                 BMAKE: Add autecl entry to batch file and sestbl.   Tregoning 951005
c version 9.60    CHDRED, IMAKEF, NXEPOC, NXSAT, SESCHK, XCHECK, XCSATS:  Add receiver and
c                    antenna id to CHDRED and lib/xhdred call.   King 951019
c                 IMAKEF:  Remove extraneous '1' in column 1 of 'include dimpar.fti' line. King 951019
c version 9.61    FIXDRV: New hisub argument list added, plus antmod.dat file checked. McClusky 951020
c version 9.62    SOMAKE: Fix failure to warn about satellites with new-style constraint line. King 951114
c version 9.63    Makefile: Variable ranlib for compatiblity with Solaris 2.  Fang/King 951208
c                 Makefile: Remove extra spaces after last DORANLIB.  Fang/King 951222
c                 BMAKE: Set arcout file name from t-file extent rather than day number. King 951229
c version 9.64    SOMAKE: Rewrite free format character reads (for DEC).  Tregoning 960102
c                 XCSATS:  Fix double comma causing segmentation fault with C-file input.
c                         Tregoning 960104/960118
c                 SOMAKE: Fix bug in call to read_line.  Herring/Tregoning  960112
c version 9.65    FIXDRV, SESCHK: Get start time for test call to rstnfo.  King 960122
c                 BMAKE:  Fix problem with multi-session for 0-iter with clean data  (not allowed
c                     for 1- or 2-iteration, quick, or unclean data); don't call autecl if
c                     AUTCLN not being run.  King 960127
c                 SOMAKE: Fix failure to warn about satellites with 15-parameter constraint line
c                     in case of separate lines for each satellite.   King 960127
c                 RDSITT: Blank out entire outgoing stream, not just first character.  King 960127
c                 CMMAKE: Fix logic for multisessions; fix test on NZEN missing in sittbl. and
c                      fix warning.  King 960127
c                 SOMAKE: Change pointers for reading error models from internal
c                            character strings.   Tregoning 960129
c version 9.66    Makefile and directory: Remove RSITED (not used).  King 960218
c                 SETFRE: Remove unused and unreferenced routine from directories.  King 960219
c                 Changes to incorporate status/error reporting (lib/REPORT_STAT) and to allow
c                      detection of all table entry errors in one pass:  FIXDRV, RDSITT, BMAKE,
c                      ACMAKE, ARMAKE, CMMAKE, DBMAKE, MDMAKE, NGMAKE, SCMAKE< SOMAKE.  King 960218
c                 Additional changes to incorporate status/error reporting:
c                 CLKPRM, IMAKEF, LFNTOP, NXSAT, SATNMR, SESCHK, TGSATS, XCHECK, XCSATS.  King 960219
c                 BMAKE: Fix bug with 1-ITER missing J-file.  King 960221
c                 MDMAKE: Remove extra comma in format.  Fang/King 960226
c                 FIXDRV, FVERSN: Reorder the status-file and screen messages.  King 960228
c                 FIXDRV, XCHECK: Exclude '6' from guess of year from d-file (could be '86 or
c                      '96).  King 960301
c                 CMMAKE: Fix checks and warnings for NZEN from sestbl and sittbl.  King 960302
c version 9.67    MDMAKE: Correct typo leading to bad KLOCK for MiniMac.   King 960319
c                 RDSITT: Add 'implicit none'.   King 960320
c                 FIXDRV: Decrease character length of 'kfiles', increase 'message'.  King 960326
c                 BMAKE:  Change comment written with 'rm *.status', etc. lines.  King 960327
c                 BMAKE,  CMMAKE,SOMAKE: Force use of m-file value of nzen.  King 960328/960401
c                 BMAKE:  Implement removal of status files in a machine-independent way.  King 960402
c                 SOMAKE: Remove / from format for internal write.  King 960406
c                 SESCHK: Replace '' string with ' ' in report_stat call (DEC bug) Tregoning 960527
c                 CMMAKE: Set number zenith delays from sittbl. value for SOLVE batch file.  King 960529
c                 BMAKE: Remove debug with quick option.  King 960529
c         9.68    BMAKE: Fix bug in updating c-file 6th letter when c-file input.  King 960612
c                 SOMAKE: Always put spaces between coordinate a priori entries.  King 960701
c         9.69    Changes for new kf/gamit structure and Makefiles from unimake.  King 960718
c                        All routines:  removed trailing blanks and replaced lib/*.fti 
c                        includes by ../includes/*.h.    
c         9.70    BMAKE: Make default for 'Final ARC' no instead of yes.
c                 ARMAKE: Make default inertial frame J2000 instead of B1950.  King 960930 
c                 MDMAKE: Make default itide = 3 (include freq-dep terms).  King 961001  
c         9.71    SOMAKE: Add atmospheric gradients.  King 961017 
c                 FIXDRV, XCHECK: Change 'rcvers' => 'swvers' to match lib/rstnfo.  King 970111
c         9.72    G77 compiler changes:  BMAKE, FIXDRV, NXSAT, RDSITT, SESCHK, SOMAKE: 
c                    Initialised previously uninitialised variables, removed unused variables,
c                     and explicitly typed all unexplicitly typed variables. McClusky 970110
c         9.73    MDMAKE: Change default mapping functions to Niell (NMFH, NMFW); fix bug to allow 
c                    omission of met surface P, T, H values in sittbl.  King 970123 
c                 FIXDRV:  Stop gracefully if d-file not found.  King 970129   
c                 SATNMR, TGSATS:  Get the SV list for ARC from the g-file not the t-file. McClusky/ King 970226
c                 BMAKE:  Fix warning/fatal messages for missing SV.  McClusky/King 970226
c         9.74    FIXDRV: Replace call to lib/ordsit with call to lib/sort_string.   King 970307/970321
c                 TGSATS,BMAKE: Replace efixed with new use of "frame" variable.   Tregoning 970321
c                 FIXDRV: Add trap for mismatch in # and list of X-files.  King 970430  
c                 BMAKE: Comment out '99' '999' code.  King 970505  
c                 FIXDRV, SESCHK:  Call new routine even_minute to allow X/C files with start times 
c                       mismatched by receiver firmware to be aligned and on the correct day.  King 970506
c         9.75    FIXDRV, FVERSN, IMAKEF: Add 'fixdrv.out' file to record clock info.  King 970506
c                 BMAKE: Minor format change.  King 970506
c                 IMAKEF: Add arguments to clkera call (leave behavior same for now). King 970522
c                 IMAKEF: Define character 'day' for K-file name (uncomment previously commented
c                      read of X-file name.   King 970606  
c         9.76    ACMAKE, BMAKE:  Add postfit mode for autcln.  King 970610
c                 ACMAKE, BMAKE:  Replace direct calls of avedit and autecl by new script 
c                    sh_autedit to autcln.cmd.prefit and autcln.cmd.postfit from a base 
c                    autcln.cmd file.  King/McClusky 970618 
c                 ACMAKE, BMAKE, SOMAKE: Save the q-file from the pre-fit autcln solution as 'p'
c                    so that it's not overwritten by the 'a' q-file. (Possibly temporary)  King 970620
c         9.77    SOMAKE: Fix 'missing wldmax/nldmax' message to be more elucidating.  King 970908 
c                 FIXDRV, CMMAKE, MDMAKE,SOMAKE: Trap sittbl. I/O errors.  King 970908
c                 RDSITT:  Add a default 'ALL ' entry, overridden by specific site names.  King 970919  
c                 SOMAKE: Fix report_stat message for bad coordinate constraints.  King 970920
c         9.78    BMAKE: Trap incompatibility between Iterate = C and Delete Input AUTCLN C-files = Y. King 971014
c                 IMAKEF: Fix warning message for no x-file.  King 971205 
c                 IMAKEF: Set jump-fit default to linear; make sure clkfit = blank if not input.   King 971205 
c         9.79    FIXDRV, Makefile: Add new subroutine DCHECK to check X-files and remove them from the 
c                     D-file if they don't exist; remove obsolete multi-solution loop.  King 971218
c                 SOMAKE: Add controls for different quick or pre-fit decimation factor and forcorrelation 
c                     print control; fix missing 'exit set' for tight solutions; don't write bias-fixed
c                     parameters for LC_ONLY case, nor wide-lane for L1 or L2 separate or only.  King 971230    
c         9.80    BMAKE, MDMAKE:  Move sestbl. read for yaw up a level and construct a call for
c                     yawtab in the batch file.  King 980107   
c                 ACMAKE, BMAKE:  Make mvcf conditional on non-existence of GAMIT.fatal.   King 980116 
c         9.81    BMAKE: Fix bug leading to nulls in batch file when Delete eclipse data = No.  Herring/King 980122 
c                 DCHECK:  Warn if X-files compressed, but don't removed the station from the d-file. King 980122
c                 FIXDRV, FVERSN:  Write a new print file only if clocks being recalculated.  Herring/King 980122
c                 XCHECK: Add X-file name to warning message.  King 980122
c                 DCHECK: Remove duplicate declaration.  King 980211  
c                 SOMAKE: Add control for different observable for quick or pre-fit run;
c                      simplify code for pre-quick decimation.  King 980213   
c                 SOMAKE: Fix 980213 bug in pre-quick decimation.     King 980213
c         9.82    BMAKE: Add calculation interval to yawtab arguments.  King 980227
c                 TGSATS: Fix call to report_stat.  King 980227  
c                 BMAKE: Remove calculation interval to yawtab arguments (hard-wired in
c                      yawtab.  Tregoning/King 980301    
c         9.83    BMAKE, Makefile, remove SCMAKE:  Use command-line arguments for scandd to facilitate
c                      running with post-fit autcln.  King 980304  
c         9.84    ARMAKE:  Change default rad model to BERNE.  King 980310   
c                 SOMAKE: Fix bug in writing elevation-dependent error when = 0.  King 980422
c                 SOMAKE: Add 'Quick-pre Elevation Cutoff' option (sestbl. only). King 980522
c         9.85    FIXDRV: Replace gamit/lib sb pickfn.f with libraries/comlib pickfn.c.  Fang/McClusky,King 980720
c                 BMAKE, FIXDRV, MDMAKE: Get 'klock' initially from station.info receiver code,
c                      overriding with sittbl. value if present.  King 980720
c                 FIXDRV: Blank out k-file buffer before calling getdir.  King 980721
c                 SOMAKE: Set default for blank sittbl. cutoff entry to sestbl. value, not 15.  Foster/King 980724
c         9.86    FIXDRV, BMAKE, SOMAKE: Write fixdrv version # in solve batch file; add 'Use N-file' 
c                      option for solve.   King 980727
c         9.87    ARMAKE, BMAKE, NGMAKE:  Declare passed integers I*4 not just 'integer' to
c                      satisfy GCC on Linux; BMAKE rearrange arguments for mdmake calls; 
c                      SOMAKE: add comma to format.  King 980817
c                 FIXDRV: Search only for files starting with lowercase 'd' to avoid conflict with
c                      autcln phase residual files (usually 'DPHS').  King 980821
c                 DCHECK: Fix reading of J-file name to work with multi-session.  King 980901
c                 FIXDRV: Fix problem calling pickfn.  Herring/King 980905
c         9.88    CMMAKE, SOMAKE: Add SV antenna offsets.  King 980909 
c                 CHDRED, SESCHK:  Add 'norb' to calling arguments for lib/readc2.  King 980911
c                 BMAKE:  Use separate command to exit before 2d autcln if 'fatal' exists.  Herring/King 980915
c                 BMAKE, CMMAKE, SOMAKE: Allow for multiple gradient parameters.  King 980917
c                 CLKPRM: Catch file-error reads.  King 980921
c                 CMMAKE: Fix bug in reading sestbl. gradient command.  King 981005
c                 SOMAKE: Fix bug in reading apriori for individual SVs; fix report_stat call.  King 981005
c                 CMMAKE: Fix bug in setting # gradient parameters.  King 981006
c                 BMAKE:  Add name of N-file script.  King 981007  
c                 FIXDRV, SESCHK: If x-files compressed, get yr,doy from reading I- or K-file.  King 981013
c                 CMMAKE: Make sestbl. entry for gradients consistent with somake (use singular 'gradient'
c                     since this will allow plural 'gradients' to work also.  Tregoning/King 981022
c                 SOMAKE: Fix loose_apr_svant output string.  King 981022   
c         9.89    SOMAKE: Fix elev cut set for case of no decimal point in sittbl. and no sestbl. entry.  King 981110
c                 SOMAKE: Make EOP default=15 for orbits, still =0 for baseline; add comment about no h-file 
c                     written for prefit solution unless hmode = 'ALL'.   King 981112
c                 BMAKE, CMMAKE: Allow input of zenith- and gradient-delay intervals in hours
c                     ('Interval zen', 'Interval grad'), overriding 'Num Zen' and 'Num grad'.  Behr/King 981123 
c                 ACMAKE: Use separate command to exit before 2d autcln if 'fatal' exists.  King 981127
c                 BMAKE, FIXDRV, MDMAKE: Add 'Simulation control' to sestbl. and use to write MODEL batch file.  King 981
c                 XCSATS: Add trap for 'xorc' neither 'x' nor 'c'.  King 981230
c                 BMAKE, SOMAKE:  Remove unused ifile name from call.  King 981230
c                 DCHECK: Fix subroutine name in report_stat call.  King 981230
c                 Remove implicit statement to statisfy SGI compiler, and add implicit none;
c                    all routines compiled ok previously with explicit compiler switch:
c                    CLKPRM, NGMAKE, NXSAT, TGSATS.  Morgan/King 981231
c                 BMAKE: Remove redundant (and erroneous) comma in call to cmmake.   Herring/King 990119
c                 XCHECK: Remove slash in internal write to message for report_stat.  King 990119
c         9.90    BMAKE: Change argument for sh_sigelv from autcln.sum.post to autcln.cmd.post.  `
c                     Herring/McClusky/King  990119
c                 FIXDRV: Initialize sestbl/sittbl error flags.  Morgan/King 990310    
c         9.91    MDMAKE: Force use of new (Ray) short-period UT1/pole model.  Herring/King 990320
c                 MDMAKE: Make pole-tide 'on' default.  King 990320
c                 BMAKE: Do not use comma as continuation character (IBM and f90 restriction).  Fang/King 990324
c                 SOMAKE: Simplify read of site constraints (probably not necessary).  King 990324
c                 SOMAKE: Add 'Update tolerance' for L-file coordinates (default 0.3 m).  King 990330
c                 SOMAKE: Make FIX column of sittbl. optional; set default = 'YYY'.  King 990330
c                 SOMAKE: Make CLK column of sittbl. optional, disallow estimation of
c                     station clock rate and acceleration.  King 990331 
c                 MDMAKE: Fix format of model batch file for temperatures < -9.9 C.  Herring 990330 
c                 MDMAKE: Fix bug in setting 4-bit of diurnal tide.  King 990416
c                 FIXDRV, TGSATS: Add report_stat calls for cases when fcheck shows file exists
c                     (i.e. link exists on Solaris) but file itself not there.   King 990426
c                 SESCHK: change WARNING to FATAL when scenarios of X- (or C-) file
c                           is different to session.info    Tregoning 990505
c                 SOMAKE: Add iostat check for reading station constraints.  King 990505
c         9.92    BMAKE: Update L-file for autcln postfit solution if requested.  King 990628
c         9.93    Changes for 4-digit years: ARMAKE, BMAKE, FIXDRV, IMAKEF, NGMAKE, XCSATS.  King 990727
c                 BMAKE: Add optional redo of AUTCLN with new M-file. ('autcln post = 'R'  Herring/King 990809
c                 BMAKE, SOMAKE, SESCHK: Add argument to lib/rsesfo call.  King 990817
c                 BMAKE: Fix bug in redo feature.  King 990823     
c                 BMAKE: Fix bug in rms check message.  King 990908
c                 BMAKE,MDMAKE,XCHECK: Use X-file flag to determine static or kinematic.   Bock 991120
c         9.94    BMAKE:  Error in writing command-line argument for sh_sigelv; also change * to # in comment.  
c                          Agnew/King 000113
c                 SOMAKE: Remove comma in format, fix spelling.  Fang/King 000215
c                 FIXDRV: Fix message for wrong l-file name in d-file.  King 000215
c                 SESCHK: Fix bug in getting day number for X/C-files written in UTC.  King 000310
c                 BMAKE: Add 'endif' for redo section.  King 000310
c                 SOMAKE: Change format for ionospheric constraint.  Bock 000428
c         9.95    BMAKE, MDMAKE: Add line to batch file to create a u-file for ocean tides;
c                    move reading of tide control from MDMAKE to BMAKE.  King 000721 
c                 CMMAKE: Fix logical error in checking nzen from sittbl.  King 000817
c         9.96    SOMAKE: Fix incorrect setting of ierr_sittbl for sestbl error in orbital constraints. King 010102
c                 FIXDRV: Change trivial logical error in if/then.  King 010102
c                 RDSITT: Initialize ILL to avoid false warning/fatal.  King 010102
c                 SOMAKE: Changes for SOLVEL (lambda ambiguity resolution and epoch-by-epoch processing). Bock 001116 
c                 FIXDRV: Get correct clock model in multisession mode.  Ming Wang 000302/King 010103
c                 SOMAKE: Make SOLVEL sestbl. entries optional. King 010102
c                 SOMAKE: Change missing X-file, session.info message to report_stat call. King 010102
c                 SOMAKE: Make SOLVE options optional; add report_stat calls.  King 010104
c         9.97    BMAKE: Remove space between #! and /bin/csh in batch file.  Ling Zhang / King 010222
c                 BMAKE: Redirect rm for status, warning, fatal to dev/null.   King 010306
c                 FIXDRV, BMAKE: Send almost all output now to fixdrv.out.  King 010309
c                 BMAKE: Avoid null string in report_stat call.  Tregoning/King 010518  
c                 BMAKE: Add iostat to open and write of batch file, to trap permission problem.  King 010619  
c         9.98    FIXDRV: Convert sname to uppercase immediately to avoid odd message if station.info missing. King 010620 
c                 BMAKE:  Move test on overwritting a T-file with partials until after the header is read.  King 010719   
c                 SESCHK: Sort the X- or C-file SVs before checking.   McClusky/King 010828
c         9.99    FIXDRV, CHECK: Allow reading of new-style station.info; change 'swver' from R*8 to R*4
c                           to match rest of GAMIT.  King 020308     
c                 MDMAKE: Change screen warning to report_stat call for mismatched ant phase model.  King 020319
c        10.01    MDMAKE: Add comments for met models.   King 020705   
c        10.02    FIXDRV, BMAKE: Allow use and name-update of apr as well as l-files.  King 020807 
c                 Makefile: move UPNAM2 to /lib to be consistent with upnam1 and upnam3.  King 020807 
c        10.03    BMAKE: Change Earth tide default to include ocean loading.  King 021029  
c        10.04    SOMAKE: Tightenn loose constraints for coordinates, orbits, SV antennas offsets, and
c                            EOP by a factor of ten.   King 021209
c        10.05    ARMAKE: Allowed EGM96 gravity field in arc.  Herring 030304.  
c                 BMAKE: Option to use satellite reweighting if 'Use N-file = S'.  King 030319   
c                 BMAKE: Add 'N-file = S' option to 'repeat' (last) SOLVE run (overlooked in 030319 change). Herring/King 030401
c        10.06    FIXDRV: Remove obsolete 'icall' from call to hisub.  King 030418         
c                 MDMAKE: Add SV antenna model to sestbl. and MODEL batch file.  King 030425
c                 BMAKE:  Fix length of string iniitializing 'typana' for simulation.  King 031027 
c                 NGMAKE: Replace function lowerc by subroutine lowers.  King 031027
c                 FIXDRV, SESCHK: Fix k-file name length in assinging buff80.  King 031027   
c        10.07    SOMAKE: Replace LC_RANGE option by LC_AUTCLN for SOLVE.  King 031209  
c                 SOMAKE: Fix excess line length in report_stat calls.  King 031212
c                 SOMAKE: Enlarge format for maximum baseline length in ambiguity resolution. Herring/King 031216
c                 BMAKE, MDMAKE, GRDMAKE (new routine): add code for reading of grid
c                    files for atmospheric loading and IMF/VMF mapping functions. Tregoning 040107
c        10.08    SOMAKE: Fix bug in turning on estimation of SV antenna offsets.  King 040201
c                 BMAKE: Fix bug in stop day (if not same as start) for integration in simulation mode. Tregoning 040524
c                 NXEPOC: Fix bug in attempting to open c-file in simulation mode.  King 040525       
c                 BMAKE: Skip check on rms in simulation mode. King 040525
c                 MDMAKE: Allow printing of zenith delays into Z-file; change convention for
c                    b-file entry of W- and Z-files (see also MODEL). King 040611/040525/040628
c                 CMMAKE, SOMAKE: Change trap on maxnet to report_stat fatal.  King 040612
c        10.09    FIXDRV, BMAKE, MDMAKE, SOMAKE: Add optional scratch directory name.  King 041018
c        10.10    CHDRED, SESCHK: Revised c-file format for models.  King 050201
c                 IMAKEF, SESCHK, XCHECK, XCSATS: Remove 'extra' from call to /lib/xhdred.  King 050201 
c                 MDMAKE: Add E-tide model, atmospheric loading, and hydrological loading to datum line. King 050209
c        10.11    SOMAKE: Set elevation cutoff default to 0. to use AUTCLN cutoff.  King 050216
c                 BMAKE, MDMAKE: Change 'Tide model' to 'Tides applied' (with backward compatibility) and 
c                    and 'Etide model' for the solid-Earth tide (IERS96 or IERS03); change
c                   comments in batch file so that all first words are capitalized.  King 050217
c        10.12    BMAKE, MDMAKE: Correct name of old e-tide model to IERS92 (not IERS96). Watson/King 050218 
c                 SOMAKE: Trap illogical LC_AUTCLN for prefit solution.  Herring/King 050222
c                 BMAKE: Initialize 'eclopt' to blank to avoid writing non-ascii charcters to b-file. Herring/King 050222
c                 ARMAKE: Allow turning off lunar eclipses.  King 050223
c        10.13    BMAKE:  Add option to use or not stations.oct for ocean tides (default 'no', use grid). King 050420
c        10.14    BMAKE, SOMAKE: Allow writing of n-file for lc_autcln even if no error reweighting; 
c                   trap obsolete 'Measurement Error' as sestbl. entry.  King 050503
c        10.15    FIXDRV: Add radome to hisub call.  King 050618
c                 FIXDRV: Add 'warnings' variable to hisub call.  King 050719
c                 MDMAKE: Allow just the site name for the w-file.  Shimada 050720
c        10.16    SOMAKE: Compare autcln command file with sestbl for 'lc_autcln'. King 050819    
c                 BAMKE, GRDMAKE:  New code for applying atm tides. Tregoning 050509/050906
c        10.17    FIXDRV: Replace hisub with hisub2 to check availabilty of antenna dimensions.  King 051029
c                 BMAKE: Change default of 'Tides applied ' to 31 to include removal of mean pole of 2000
c                    from pole tide calcualtion; change default solid-Earth model to IERS03.  King 051101
c                 BMAKE: Fix bug for case of E-tide model missing from sestbl.  King 051116
c                 SESCHK: Fix bug in getting yr, doy from i-file.  King 051116
c                 XCHECK: Fix bug in missing callling argument for rstnfo2.  King 051116  
c         10.18   BMAKE, GRDMAKE:  Add the VMF1 mapping function    Tregoning/King 060227
c         10.19   FIXDRV, BMAKE, SMAKE: Allow more sestbl entries to be omitted. King 060627
c                 BMAKE: Remove extraneous / in csh command of bat file.  Herring/King 060628
c                 BMAKE: Add check for system abort in SOLVE.  King 060628
c                 FIXDRV: No longer erase the status/warning/fatal files before running; this
c                   necessary to accommodate change to write to GAMIT.status/warning/fatal. King 060626  
c                 BMAKE, MDMAKE: add reading of met data from rinex file  Tregoning 060612 / King060630
c                 BMAKE: Make L_ONLY default for L/T updating.  King 060704
c                 SOMAKE: Make 'N' default for orbital constraints.  King 060704
c                 SOMAKE: Add iostat to read for elevation cutoff angle.  King 060809
c         10.20   FIXDRV, ACMAKE, BMAKE, MDMAKE, SESCHK, SOMAKE, Makefile (remove grdmake):  
c                   Add sestbl inputs for met models, mapping functions, and list/grid files; 
c                   write line for new grdtab in batch file; remove multisession option (not 
c                   needed and worked for only some options); remove sincln/dblcln options. King 060902
c                 BMAKE: Add default for deleting autcln input c-files.  Tregoning/King 060905
c                 SOMAKE; Fix bug in test for blank elevation cutoff.  Shimada 060914   
c                 ATMDEL: Fix report_stat messages.  Shimada 060914
c                 LININTERP: fix roundoff bug for last epoch of the day  Tregoning 060926   
c                 SITCOR: Fix roundoff bug in getting decimal day for atml interpolation.  Tregoning/King 060926
c                 MDMAKE: Change default rcvr antenna model from NONE to ELEV.  King 060929
c                 BMAKE:  Change default for deleting autcln C-file from N to Y (safer for surveys).  Herring/King 060929 
c                 ACMAKE: Change name of variable delsin->delaut, for clarity.  King 060929 
c                 BMAKE:  Allow override of implicit 'Autcln Posfit' settings.  King 060929 
c                 BMAKE:  Trap unallowed 1-ITER + Autcln Postfit = N.  King 060929
c         10.21   SOMAKE:  Add controls for screen print and apr bias weighting.  King 061030
c                 SESCHK: Remove extra comma in call to rsesfo.  McClusky 061105
c                 BMAKE: Fix logic with 'ITER' compatibility in case of clean data.  King 061107
c                 BMAKE: Temporarily comment out sh_chksolve lines.  King 061108
c                 SOMAKE: Fix format statement for orbit constraints (problem w/ gFortran) McClusky 061108
c                 BMAKE: Restore sh_chksolve lines but for new version (no arguments).  King 061109
c         10.22   BMAKE: Change default for 'Initial Arc' to be Yes even for BASELINE mode.  King 061204
c         10.23   BMAKE, SESCHK: SOMAKE: Change arguments for rsesfo (see lib/lversn.f). King 061207   
c                 MDMAKE: Alias 'GMF' to 'GMFH' and 'GMFW'.  King 061214
c                 BMAKE: Fix missing -sv with N-file reweighting with (default) 'R' option.  Wang/King 061219
c                 SATNMR: Trap # SVs on g-file > maxsat.  King 061227
c                 FIXDRV, BMAKE, SESCHK: Change 'FIXDRV.warning' to 'GAMIT.warning' in messages. King 061227
c                 BMAKE: Initialized 'idatum' to zero.  Herring 061229
c                 DCHECK: Remove multisession code and trap #sites > 99.  King 070104
c                 BMAKE: Fix calculation of grdtab span when start time not 0h UTC.  King 070104
c                 XCHECK: Fix erroneous assignment of 2-digit year.  King 070104
c         10.24   BMAKE (sh_sigelv): Always write an N-file for final solution, always
c                   including constraint loosening; change 'Use N-file' to 'AUTCLN reweight'. King 070119
c                 SOMAKE; Allow turning off NL sigma rescaling (hidden feature).  King 070309
c                 SESCHK: Fix #SV count in report_stat message about session.info/x-file mismatch. King 070309
c                 DCHECK: Trap # sites > maxsit.  Charade/King 070313
c                 SOMAKE: Allow input of the condition number for removing dependent biases.  McClusky/King 070319
c                 BMAKE: Fix span calculation to round up to the nearest 0.25 days.  Floyd/King 070322
c                 SOMAKE: Set default for bias a priori to 1000. (rather than zero) and condition number to 100. 
c                     Herring/McClusky/King 070409
c                 FVERSN: Remove print unit number from 'lversn' call.  King 070416 
c                 BMAKE: Tweak span calculation to avoid overshoot for mutliples of 6-hrs; write out
c                   span in days to 2-decimal places.  Floyd/King 070417                        
c                 SOMAKE: Add (undocumented) option for bias-fixing debug. McClusky/Herring/King 070430.c
c         10.25   SOMAKE: Set default rcond (ier 140 in matrix inversion) high (10000.) to avoid missing an
c                     independent bias.  Herring/McClusky/King 070501
c         10.26   SOMAKE: Set loose-solution constraints tighter (1m) for L1 and/or L2 observations,
c                     assumed to be short baselines.  King 070724   
c                 BMAKE, MDMAKE: Add source of 2nd and 3rd order ionosphere corrections to MODEL batch file. King 070730
c                 ACMAKE: Set ierr_sestb=0 to avoid warning of unused variable.  King 070907 
c                 CHDRED, IMAKEF, NXSAT, XCSATS: Removed unused 'iscrn' from calling argument. King 070907 
c                 CLKPRM: Comment out unused format statements.  King 070907
c                 BMAKE, CMMAKE, FIXDRV, SOMAKE: Remove unused calling arguments 'sestbl', 'sittbl'.  King 070907
c                 FIXDRV, FVERSN: Remove unused calling argument 'lscrn'. King 070907 
c                 FIXDRV, IMAKEF: Removed unused calling argument 'lsite'.  King 070907
c                 FIXDRV, SESCHK, TGSATS: Remove unused calling arguments.  King 070907  
c                 SOMAKE : Remove unused calling argumeent and statement number. King 070907
c                 BMAKE: Fix bug in setting f-file name for ionosphere.  King 071115
c                 ARMAKE: Change default gravity field to EGM96.  King 071227 
c                 BMAKE: Fix the span for grdtab to extend 6hr beyond last observation (for interpolation).  King 080125
c                 SOMAKE: Increase format size for 'rcond'.  Herring/McClusky 080131
c                 BMAKE: Fix potential bug in reading 'Tides applied'.  Herring/King 080220
c                 SOMAKE: Fix bug in reading elevation cutoff when decimal point missing.  King 080314
c                 BMAKE: Minor fix to check for missing metsource (probably no effect). King 080317
c         10.27   BMAKE: Change fatal to warning for SV missing from t,g file.  King 080502
c                 IMAKEF, SESCHK, XCHECK, XCSATS: Change antenna offset variable in call to /lib/xdred.  King 080509
c                 FIXDRV, XCHECK:  Remove calls to old rstnfo, rename rstnfo2 to rstnfo.  King 080509   
c         10.28   SOMAKE: Allow skipping the loose solutions.  King 080905
c                 BMAKE: Set grdtab to produce put VMF1 values on u-file if 'UFL' set first for 'Met source'. 
c                       Allows VMF1 ZHD even if the mapping function is to be something else. King 081110
c                 MDMAKE: Add reminder of GPT or SPT last to fatal message in reading 'met obs source'. King 081120
c                 SOMAKE: Remove case sensitivity from check for 'lc_autcln' in autcn.cmd.  King 081205
c                 BMAKE: Change logic so that obsolete 'Use N-file' doesn't override 'AUTCLN reweight'. King 081208
c         10.29   BMAKE, CMMAKE, SOMAKE: Fix setting of nzen/ngrad for 'con' model; clean up zenith/gradient
c                   code; remove obsolete 'quick' and lamba-method code for solve.  King 090501
c                 BMAKE, MDMAKE: Add undocumented option for dipole rather than IGRF.  King/Petrie 090505  
c                 BMAKE:  Fix bug in 090501 changes, create correct q-file name for full solution, King 090522
c                 BMAKE: Fix up logic for iterations with old scheme (0-ITE + autcln_post)  King 090528
c                 BMAKE: Fix bug in setting default number of gradient parameters.  King 090529
c                 BMAKE: Fix file-name in fatal message for missing met grid file.  King 090601
c         10.30   BMAKE: Fix bug when 'Data Status = CLN' in sestbl.  Shimada 090707
c                 BMAKE: Fix bug when 'Quick-pre observable = LC' in sestbl.  Petrie/King 090728
c                 BMAKE: Fix bug in q-file name for sh_sigelv (introduced 090522). King 090728
c                 FIXDRV, BMAKE:  Fix bugs in setting times for simulations.  King 090826
c                 SOMAKE: Remove unnecessary (and buggy) writing out of format for ionospheric constraints. King 090826
c         10.31   FIXDRV, XCHECK: Remove unused 'trkcod' from call to rstnfo; remove calls to 
c                     obsolete check_oldstnfo. King 100209
c                 BMAKE: Fix bug in setting # zenith and # gradient parameters if sestbl input is the 
c                    interval.  King 100217 
c                 ACMAKE: Add line to echo 'autcln is running--see autcln.out for messages' to screen log. King 100716
c                 SOMAKE: Change L1-only receiver test from 'L1_SINGLE' to "L1_RECEIVER'. King 100818
c                 MDMAKE Change default ground antenna model to AZEL and SV to ELEV.  King 100819
c         10.32   SESCHK: Add new C-file variables to readc2 call.  King 100827
c                 FIXDRV, XCHECK: Add rcvers, rcvrsn, antsn to rstnfo calls. King 100908/101022
c                 BMAKE: Allow IGRF10 and IGRF11 as well as DIPOLE for the magnetic field. Petrie/King 101012
c                 FIXDRV: Trap empty i-file. King 101022
c                 BMAKE: Make IGRF11 default magnetic field.  Petrie/King 101022
c         10.33   ARMAKE: Fix bogus test on year > 2010.  King 110101/110103
c                 ARMAKE: Allow UCLR1 radiation-pressure model.  Petrie/King 110124
c                 MDMAKE: Allow IERS2010 model for short-period EOP (Ray still default). Herring 110210
c         10.34   ARMAKE:  Allow EGM08 gravity field ('refsys') without a fatal (EGM96 still default). King110418
c                 MDMAKE: Fix comments for 'Ionsophere source' in b-file.  King 110629
c                 BMAKE: Allow misspelling of 'L1,L2_INDEPENDENT' to be reconginzed. King 110818
c                 MDMAKE: Fix typo in comments (ITRF11->IGRF11)
c         10.35   MDMAKE: Change short-period EOP default to IERS10.  King 111228
c                 ARMAKE: Change gravity field default to EGM08.  King 111228
c         10.36   Makefile, READ_SESTBL: New program, callable from scripts, to read the sestbl. King 120514
c                 ARMAKE: Add reading of an Earth radiation model, an antenna thrust model, and the debug
c                      print flag from the sestbl..  King 120523
c                 BMAKE:  Add a repeat integration following the creation of the yaw file.   King 120523
c         10.37   MDMAKE: Replace the obsolete elevation cutoff-angle with a Y/N question about using
c                      a site-specific antenna model.  King 120726
c         10.38   CHDRED, SESCHK: Add two variables to the readc2 call.  King 130115
c         10.39   TGSATS: Add Earth radiation and antenna radiation models to thdred call. King 130320
c                 ACMAKE, BMAKE: Add 'AUTCLN clocks' option.  King/Herring/Moore 130328
c                 FIXDRV: Fix problem writing a time-date header to the print file when no open. King 130328
c         10.40   BMAKE: Change calling arguments for yawtab and sh_autedit for new yaw implementation. King 140204
c         10.41   ARMAKE: Allow 'EGR08' reference frame for ARC for testing relativity.  King 140401
c                 CHDRED, SESCHK: Add variables to the c-file header.  King 140401
c         10.42   BMAKE, MDMAKE: Add IGRF12 (now default) to the magnetic field options.  Shimada 150123
c         10.43   Major mods to change c-file format and support GNSS: Makefile, ARMAKE, BMAKE, CDHRED, IMAKEF
c                    MDMAKE,NXEPOC, NXSAT, SESCHK, TGSATS, XCHECK, XCSATS; remove obsolete SATNRM.  King 150123
c         10.44   BMAKE; Fix typo in name of magfield. Herring/King 150617
c                 MDMAKE: Set dzen and wzen to VMF1 if metmod is UFL and mapping functions are VMF1. Floyd/King 150728
c         10.45   CMMAKE, SOMAKE: Change formats to accommodate nzen > 99.  King 170324
c         10.46   IMAKEF, SESCHK, XCHECK, XCSATS: Add obervable types for call to lib/xhdred.  King 170525 
c         10.47   ARMAKE: Add controls for the degree of the static gravity field, solid-Earth tides, and ocean tides. King 170911
c                 FIXDRV: Don't execute if a previous GAMIT.fatal exists (from MAKEX or MAKEX). King 170919
c         10.48   BMAKE, IMAKEF, MDMAKE, SESCHKXHCECK, XCSATS: Replace obsolete SKD code with GNSS 
c                     code in MODEL b-file and calls to lib/xhdred. King 180322
c                 FIXDRV, XCHECK: Remove obsolete 'skd' from calling arguments to lib/rstnfo. King 180322
c                 FIXDRV, BMAKE, DCHECK: Chenge the 1st d-file entry to the GNSS code; add global.h. King 180427
c                 FIXDRV: Allow '1' in first line of d-file for backward compatibility.  Herring/King 180611
c         10.49   FIXDRV, ACMAKE, BMAKE, CMMAKE, SOMAKE: Change 'maxnet' and 'max_fixdrv_sitess' to 'maxsit' and 
c                    remove fixdrv.h since multi-session no longer supported. King 190502
c                 ARMAKE, SOMAKE: Extend loose-constraints option to allow 19 orbital paramaters for ECOMC. King 190523
c                 ARMAKE: Added 'ARC plamets' to turn on lbody in arc Herring 190622.
c         10.49   ARMAKE: Allow use of new IAU sofa inertial RF models (IAU0A, IAU0C and IAU06). McClusky 190801 
c         10.50   No documentation
c         10.51   BMAKE: Added IGRF13 as option and default.(Consolidate all IGRF routines in future) 
c                 Cleaned up fvern as well.  Herring 200125.
c                 CHDRED (different from other CHDRED routines),SESCHK:  Updated for L1/L2 Satellite PCO values in c-file
c                   svantdx(2,3,nsat) Herring 200126. 
c                 FIXDR, XCHECK Added antdaz, Ground antenna azimuth Herring 200205.
c                 MDMAKE: changed ietide format to allow values >99.  Herring 200219.
c                 ARMAKE: Set default precession to IAU0A and default refsys EGR08.  Herring 200304.
c                 SESCHK: Updated 32I to 50I to allow for 35 Beidou satellites TAH 200618
c         10.52   DCHECK: Changed variable "nsoln" (integer*4) to "gnss"
c                 (character*1) to ensure accurate rewriting of d-file
c                 header when "edit_needed" is true, following makexp
c                 scheme, and replaced skipping of GNSS code and #
c                 sessions information with definition of "gnss" and
c                 "nsess", respectively. MAF 20210113
c
      end
