#!/bin/csh -f 
#
# Script to take 4-character orbit name and GNSS and return updated
# 4-character orbit name and sp3 file 3-char label
#
if( $#argv == 0 ) then
   echo "Usage: sh_gname <4-char orbit> <gnss>"
   echo "Return [Updated 4-char name] [3-char SP3 label]"
   echo "sh_gname mitf E returns mite mie"
   exit
endif

set inname = $1
set gnss = "g"
if( $#argv > 1 ) set gnss = `echo $2 | awk '{printf("%s",tolower(substr($1,1,1)))}'`

set out = `echo $inname | awk '{printf("%4s %3s", $1,substr($1,1,3))}'`
if( $gnss != "g" ) then
   set out = `echo $inname $gnss | awk '{printf("%3s%1s %2s%1s", substr($1,1,3),$2,substr($1,1,2),$2)}'`
endif
echo $out


