      SUBROUTINE OPNCHK(FNAME,IOFORM,IUN)
C
C     TO CHECK A FILE TO BE OPENED AND DETERMINE IF IT EXISTS AND IF
C     SO IT IS REWOUND AND WROTE OVER
C     RICK ABBOT - JANUARY 1986
C
      IMPLICIT REAL*8 (A-H,O-Z)
      CHARACTER*16 FNAME
      integer*4 ioform,iun
C
   50 READ (5,100) FNAME
  100 FORMAT (A16)
C
      IF (IOFORM.EQ.0) OPEN(UNIT=IUN,FILE=FNAME,ERR=300,STATUS='OLD',
     $       FORM='UNFORMATTED')
      IF (IOFORM.NE.0) OPEN(UNIT=IUN,FILE=FNAME,ERR=300,STATUS='OLD',
     $       FORM='FORMATTED')
      REWIND IUN
      RETURN
C
  300 IF (IOFORM.EQ.0) OPEN(UNIT=IUN,FILE=FNAME,STATUS='NEW',
     $                      FORM='UNFORMATTED')
      IF (IOFORM.NE.0) OPEN(UNIT=IUN,FILE=FNAME,STATUS='NEW',
     $                      FORM='FORMATTED')
C
C
      RETURN
      END
