*    
*  Include file containing information from external SP3 or ORBEX files,
*  GAMIT t-files, and quantities generated by programs in the gamit/orbits
*  directory.  

*  (to become orbits.h in gamit/includes or gamit/orbits, but temporraily orbits/orbitx.h)

*   maximum number of satellites on the external orbit file 
*    (may be more than the GAMIT orbsat dimensions, to account for GLONASS)
      integer   maxsv
      parameter (maxsv = 60)                        

*   maximum number of elements in the broadcast ephemeris (e- or nav) file
      integer   maxbrd                  
      parameter (maxbrd = 750)  

*   maximum number of elements in the yaw arrays 
*   max number of eclipse + noon turns is 4 per day x 2 planes x 4 SVs/plane = 32/day
*   allow for 7 days, for now, the possible length of a T-file (7*32)
      integer  maxyaw
      parameter (maxyaw = 224)

*   maximum number of t-files allowed for orbfit (ref + # days)
      integer maxtfil 
      parameter (maxtfil = 4)

*   maximum number of global (non-orbital) parameters allowed in orbfit
      integer maxglb
      parameter (maxglb = 13)       

*   maximum number of epochs in an orbit file (700 = 7-days+ at 15 minute intervals)
      integer maxsvepch
      parameter (maxsvepch = 700)          

*  Header information common to at least two file types
*        start,end time, # epochs, and interval of file
      integer*4 fstr_year,fstr_mon,fstr_day,fstr_hr,fstr_min
     .        , fend_year,fend_mon,fend_day,fend_hr,fend_min,nepoch
      real*8 fstr_sec,fend_sec,finterval,sigp(maxsv),sigclk(maxsv) 
*        PRN # of satelllites (use 1-100 for GPS, 101-199 for GLONASS, 201-299 for Galileo)
      integer*4 nsv,isv(maxsv)     
*        coordinate system and models    
      character*8 crdsys,frame
      character*20 pcvmod,otlmod,atlmod,clkmod,orbmod
      character*1  otlflg,atlflg     
*        source of file
      character*4 agency 
      common /header/fstr_year,fstr_mon,fstr_day,fstr_hr,fstr_min
     .             , fend_year,fend_mon,fend_day,fend_hr,fend_min,
     .             , fstr_sec,fend_sec,finterval,nepoch
     .             , nsv,isv,xsigavg  
    .              , precmod,nutmod,gravmod,srpmod,crdsys,frame,agency

*   Coordinates and clocks at each epoch
      real*8 x(6,maxsvepch),sigx(6,maxsvepch)
     .     , clock(maxsvepch,sigclk(maxsvepch)
      common /values/x,sigx,cloc,sigclk

      

