#!/bin/csh
if ($#argv == 0) then
   echo ' '                                       
   echo ' copy a bunch of X-files '
   echo '               '
   echo ' useage: copyx b a'
   echo ' '
   echo ' will move b-series X-files to a-series'
   echo ' '
else
 foreach file ( x????$1.??? )
   set oldser = `ls $file | awk '{print substr($1,6,1)}'`
   set newser = $2
   set code4  = `ls $file | awk '{print substr($1,2,4)}'`
   set code3  = `ls $file | awk '{print substr($1,8,3)}'`
   \mv -i x$code4$oldser.$code3 x$code4$newser.$code3
 end #for
endif

