#!/bin/csh
#
# usage:  gmtcircle lon lat radius(km)
nawk 'BEGIN {print "> Circle"; for (i = 0; i <= 360; i += 5) {print '$3' * cos(i*0.0174532925), '$3' *sin(i*0.0174532925)}}' /dev/null | mapproject -R0/360/-90/90 -JE$1/$2/1 -Fk -C -I -H1
