#!/bin/csh -e 
if ($#argv == 0) then
   echo ' '                                       
   echo ' Run SCANRMS to scan and sort post-fit residuals '
   echo '               '
   echo ' useage: scanm mfile0.123'
   echo ' '
else
   set suffix = `echo $1 | awk '{print substr($1,2,9)}'`

if (-e m$suffix) then

echo 'Running scanrms ....'

# make an unsorted list of all combinations
scanrms m$suffix >! tmp.scanm

# show output if error
if ($status != 0) then
   cat tmp.scanm
endif

\rm tmp.scanm
\mv vscan.out v$suffix
 
else
   echo 'Could not find' m$suffix
endif

# sort the list of jummps by magnitude and epoch number.
sortv v$suffix

endif

