#!/bin/csh -f
echo 'Shbasenew' > tmp.tst
echo 'a second line ' >> tmp.tst
echo $* >> tmp.tst
echo 'a forth  line ' >> tmp.tst
#/bin/csh /data3/stdrel/com/sh_basenew $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} >> tmp.tst
/bin/csh /data30/rwk/active/com/sh_baseline $*  >> tmp.tst

