#!/bin/csh 
#
#doc Compare 2 files line by line
#doc
#
if ($#argv == 0) then
   echo 'Function: ' 
   echo '  '
   echo '  Compare 2 files line by line '
   echo '  '
   echo 'Examples:'
   echo '  '
   echo '  Compare whole lines:     sh_cml a.dat b.dat '
   echo '  Compare columns 1 to 10: sh_cml a.dat b.dat 1 10'
   echo ' '
else                      
   if (-e $1 && -e $2) then
      if ($#argv == 2) then
cml <<!
1
200
$1
$2
!
      endif
      if ($#argv == 4) then
cml <<!
$3
$4
$1
$2
!
      endif
   else
      echo Missing files
   endif                
endif

