#!/bin/csh -f

# usage: chknav navigation file (compressed or uncompressed)

# return 1 if the time tag of a given navigation file is not
# in reasonable range

# by pfang@ucsd.edu 98

if ($#argv < 1) then
	sed -e "1,1 d" -e "/by pfang/q" $0
	exit
endif

set cat = 'cat'
switch($1)
	case *.Z:
	set cat = 'zcat'
	breaksw
endsw
$cat $1 | sed -e "1,/END OF/d" | \
awk 'substr($0,2,1) != " " && $1 < 0 {print 1; exit} \
substr($0,2,1) != " " && $2 < 0 {print 1; exit} \
substr($0,2,1) != " " && ($3 < 1 || $3 > 12) {print 1; exit} \
substr($0,2,1) != " " && ($4 < 1 || $4 > 31) {print 1; exit} \
substr($0,2,1) != " " && ($5 < 0 || $5 > 24) {print 1; exit} \
substr($0,2,1) != " " && ($6 < 0 || $6 > 60) {print 1; exit} \
substr($0,2,1) != " " && ($7 < 0 || $7 > 60) {print 1; exit}'
