#!/bin/csh -f
#
#doc Fix the headers of ALEX RINEX files with bogus START OF OBSERVATIONS line
#doc
#
# RWK from SCM sh_fixsst  2011/2/1
if ($#argv == 0) then
   echo ' '                                       
   echo ' Fix the headers of RINEX files with a bogus TIME OF FIRST OBS line'
   echo '   --removes the line '
   echo ' '
   echo ' Examples'                               
   echo ' '                                       
   echo '   sh_fixalex alex2340.07o'
   echo '   sh_fixalex alex*.07o'   
   echo ' '                                       
   echo ' Old files saved with extent .old'                               
   echo ' '                                       
   echo ' '                                       
exit
else 
endif 

set files = ""  
foreach i ( `echo $argv` ) 
#old	if ( `echo $i | cut -c12- ` == o) then 
	if ( `echo $i | awk '{FS="/"} {print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10}' | awk '{print $(NF)}' | cut -c12- ` == o) then 
		set files = ( $files $i ) 
	endif
end


# loop over all files
foreach file ( `echo $files ` )
   echo 'Working on ' $file
      
# output to screen
fixalex <<[
$file
[
mv $file $file.'old'
mv $file.new $file

end # foreach




