#!/bin/csh -f
#
#doc Fix the headers of SST RINEX files incorrected translated as SSE
#doc
#
# Modified for most cases S. McClusky 97/02/21
if ($#argv == 0) then
   echo ' '                                       
   echo ' Fix the headers of SST RINEX files incorrectly transated as SSE'    
   echo '   --removes P2 and set # observables = 3 '
   echo ' '
   echo ' Examples'                               
   echo ' '                                       
   echo '   sh_fixsst vndn1230.90o'
   echo '   sh_fixsst *.90o'   
   echo ' '                                       
   echo ' Old files saved with extent .old'                               
   echo ' '                                       
   echo ' '                                       
exit
else 
endif 

set files = ""  
foreach i ( `echo $argv` ) 
#old	if ( `echo $i | cut -c12- ` == o) then 
	if ( `echo $i | awk '{FS="/"} {print $1,$2,$3,$4,$5,$6,$7,$8,$9,$10}' | awk '{print $(NF)}' | cut -c12- ` == o) then 
		set files = ( $files $i ) 
	endif
end


# loop over all files
foreach file ( `echo $files ` )
   echo 'Working on ' $file
      
# output to screen
fixsst <<[
$file
[
mv $file $file.'old'
mv $file.new $file

end # foreach




