#!/bin/csh -f
#
#doc Fix the headers of old x-files missing LAMBDA values
#doc
#
if ($#argv == 0) then
   echo ' '                                       
   echo ' Fix the headers of old X-files that are missing LAMBDA values'
   echo '   (also removes specific binary characters from old x-files)'    
   echo ' '
   echo ' Examples'                               
   echo ' '                                       
   echo '   sh_fixx xalgo8.075'
   echo '   sh_fixx x*.???'   
   echo ' '                                       
   echo ' Old files saved with extent .old'                               
   echo ' '                                       
   echo ' '                                       
exit
else 
endif 

set files = ""  
foreach i ( `echo $argv` ) 
	set files = ( $files $i ) 
end


# loop over all files
foreach file ( `echo $files ` )
   echo ' ' 
   echo ' '  
   echo '***************************'
   echo ' ' 
   echo 'Working on ' $file
      
# output to screen
fixx <<[
$file
[
mv $file $file.'old'
mv $file.new $file  
echo 'Moved ' $file 'to' $file'.old'
echo 'Moved ' $file'.new' ' to ' $file

end # foreach




