#!/bin/csh 
#
#doc Scale and translate postscript files
#doc
#
# M.Burc Oral 12/10/1993

if ( $#argv == 0 ) then
echo " sh_postscript"
echo " "
echo " Scale and translate postscript files"
echo " "
echo " usage:    sh_postscript         <files>"
echo " "
echo "           sh_postscript  %value <files>"
echo " "
echo "           sh_postscript  <-x translate pixels >  <-y translate pixels >  <-s  scale factor >  <files>"
echo " "
echo " example  sh_postscript %60 postscript_file.ps"
echo " example  sh_postscript -x 10 -y 10 -s 0.6 postscript_file.ps"
echo " "
exit
endif

set scale = .925
set translate = 75

if ( `echo $argv[1] | cut -c1 ` ==  "%" ) then
   set scale      = `echo $argv[1] | cut -c2-  | awk '{print $1 / 100 } '`
   set Xtranslate = `echo $argv[1] | cut -c2-  | awk '{print ((1- ($1 / 100)) * 1000)/4 } '`
   set Ytranslate = `echo $argv[1] | cut -c2-  | awk '{print ((1- ($1 / 100)) * 1000)/2 } '`
   shift argv
endif 

if ( `echo $argv[1] | cut -c1-2 ` ==  "-x" || `echo $argv[1] | cut -c1-2 ` ==  "-y"  || `echo $argv[1] | cut -c1-2 ` ==  "-s" ) then
   set scale = 1.
   set Xtranslate = 0.
   set Ytranslate = 0.

	if ( `echo $argv[1] | cut -c1-2 ` ==  "-x") then 
		set Xtranslate = $argv[2]
		shift argv ; shift argv
	endif

	if ( `echo $argv[1] | cut -c1-2 ` ==  "-y") then 
		set Ytranslate = $argv[2]
		shift argv ; shift argv
	endif


	if ( `echo $argv[1] | cut -c1-2 ` ==  "-s") then 
		set scale = $argv[2]
		shift argv ; shift argv
	endif

endif 

foreach i ( $argv ) 
  echo " "
  echo "Modifying file: " $i  $scale $Xtranslate $Ytranslate $translate 
  echo " "
  if ( -e $i ) then 
    sed s/"\% Begin "/"  $scale $scale  scale  $Xtranslate $Ytranslate translate \% Begin "/ $i >! tmp.$i
    \mv  tmp.$i "new."$i
    echo "Modified file called: " "new."$i
  else
  echo FILE: $i does not exist.  Skipped...
endif
end
