#!/bin/csh 

if ( $#argv < 2  ) then
echo " "
echo " get the value higher than a given sets of percentage "
echo " "
echo " "
echo " "
exit
endif


set perc = ""
set infile = $1 
	foreach percent ( $argv[2-] )
	set l  = ( `cat $infile  | sort | wc | colrm 9` ) 
	set p = ` echo $l $percent | awk '{printf" %6d \n", $1 * $2 / -100  }'`
	set last = `cat   $infile | sort -n +1  | \head $p | tail -n -1 |awk '{printf"%10.2f\n",$2}' `
	set perc = ( $perc $percent $last )
	end
	echo $perc


