#!/bin/bash

# Script for updating required BLAS routines.
# Move dblas1.f, dblas2.f and dblas3.f to gamit/lib/ when finished.

# Redirect standard error to /dev/null
exec 2>/dev/null

# Download latest BLAS1, 2 and 3 routines
wget -N http://netlib.org/blas/blas1.tgz http://netlib.org/blas/blas2.tgz http://netlib.org/blas/blas3.tgz

# Unzip and expand downloaded tar-files
for i in 1 2 3; do
  tar xvfz blas$i.tgz && rm -f blas$i.tgz
done

# EITHER: Concatenate all d* routines
#cat BLAS1/d*.f BLAS1/idamax.f > dblas1.f
#cat BLAS2/d*.f BLAS2/lsame.f BLAS2/xerbla.f > dblas2.f
#cat BLAS3/d*.f > dblas3.f

# OR:
# Concatenate required routines
rm -f dblas[123].f
for routine in dgemv idamax daxpy dswap ddot dscal dnrm2 drotg dasum dcopy drot dgemm; do
  cat BLAS1/$routine.f >> dblas1.f ||
   cat BLAS2/$routine.f >> dblas2.f ||
   cat BLAS3/$routine.f >> dblas3.f
done

# Check for dependencies
for routine in $(grep -h 'EXTERNAL' dblas[123].f | sed 's/EXTERNAL//; s/,/ /g' | tr ' ' '\n' | sort -u | tr '[:upper:]' '[:lower:]'); do
  cat BLAS1/$routine.f >> dblas1.f ||
   cat BLAS2/$routine.f >> dblas2.f ||
   cat BLAS3/$routine.f >> dblas3.f
done

# Add LAPACK routine dependencies
for routine in dspr dtpmv dtpsv; do
  cat BLAS1/$routine.f >> dblas1.f ||
   cat BLAS2/$routine.f >> dblas2.f ||
   cat BLAS3/$routine.f >> dblas3.f
done

rm -fr BLAS[123]

