#!/bin/csh -f

# Copyright (c) University of California, San Diego. 1996.
# All rights reserved.

# convert year month day to year day_of_year or vise versa

# by Peng Fang  (pfang@ucsd.edu)  

if ($#argv < 1) then
	echo ""
	echo "usage: ymd2ydoy year month day (e.g. ymd2ydoy 1992 2 3 -> 1992 034) or"
	echo "       ymd2ydoy year day_of_year (e.g. ymd2ydoy 2000 81 -> 2000 03 21)"
	echo ""
	exit
endif

if ($#argv == 3) then
	echo $argv | /usr/bin/awk 'BEGIN {split("31 59 90 120 151 181 212 243 273 304 334 365",mth)} \
		{doy = mth[$2-1] + $3; \
		if (($1 - 1988) % 4 == 0 && $2 > 2) doy++; \
		printf "%d %3.3d\n",$1,doy}'
else
	echo $argv | /usr/bin/awk 'BEGIN {split("31 28 31 30 31 30 31 31 30 31 30 31",mth)} \
		{day = $2 + 0; \
		if (($1 - 1988) % 4 == 0 ) mth[2] = mth[2] + 1; \
		for (m = 1; day > mth[m]; m++) day = day - mth[m]; \
		printf "%d %2.2d %2.2d\n",$1,m,day}'
endif

