c
c EMA data for PLTSL
c ------------------
c  Each of the ema arrays are dynamically mapped so that we use
c     the smallest amount of ema and hence cut down on page swapping.
c  The ema is all contained in an array ema_data which will mapped
c     into the appropriate arrays at run time.  (See discussions in
c     FORSL)
c
c The main arrays  are:
c ---------------------
c bak_array -- the array which contains the data from the BCK_FILE
c     generated by BAKSL. See bak_file_map for description of the
c     contents of the bck_file.
c
c x_data -- the data to be plotted on the x axis.  The x axis runs
c     along the bottom of the screen.  The value and its standard
c     deviation saved.  X_data has a basic offset removed which is
c     stored in ref_valx.
c y_data -- same as x_data except for the y_axis.
c
c pt_data -- the point type data which will be used if point_type
c     is less than 0
c
      integer*4 ema_data(max_plt_space)
 
c
      common /plt_ema / ema_data
 
c
