Copyright (c) Massachusetts Institute of Technology,1986. All rights reserved.
C
      SUBROUTINE BSTAT(PHI,iphi,IOBS,IUSEBK)
C
C CONSTRUCTS SINGLE-DIFFERENCE OPERATOR

      implicit none

      include '../includes/dimpar.h'
      include 'solve.h'
C
C ISATC - DIMENSIONED TO NUMBER OF SATELLITES
C ISTATC - DIMENSIONED TO NUMBER OF STATIONS

      integer ISATC(MAXSAT),ISATX(MAXSAT),JSATX(MAXSAT),ISTATC(MAXSIT)
      integer IPHI(MAXSIT,MAXSAT)
      integer IUSEBK(MAXSIT,MAXSAT)
      integer irow1,irow2,itemp,icol1,iobs,isat,istat,icnt
     .      , jnd,ielem1,ielem2,ind1,ind2,icol2,ii,jj,ij,iii,i,j,k,l

      real*8 PHI(MAXSIT,MAXSAT)
 
c     initialize variables for G77 compiler (logic not checked)
      irow1 = 0
      irow2 = 0
      itemp = 0

C COUNT NUMBER OF STATIONS PER SATELLITE
      DO 135 I=1,nsat
  135 ISATC(I)=nsite
C COUNT NUMBER OF LIVE STATIONS PER SATELLITE
      DO 125 J=1,nsat
      DO 125 I=1,nsite
 125  IF(PHI(I,J).EQ.0.D0) ISATC(J)=ISATC(J)-1
C REMOVE USELESS ONEWAY OBSERVATIONS (LESS THAN 2 STATIONS PER SATELLITE)
      DO 3 J=1,nsat
       IF(ISATC(J).GT.1) GO TO 3
      DO 4 I=1,nsite
      PHI(I,J)=0.D0
      IPHI(I,J)=0
    4 CONTINUE
    3 CONTINUE
C
C COUNT NUMBER OF SATELLITES PER STATION
      DO 134 I=1,nsite
  134 ISTATC(I)=nsat
C COUNT NUMBER OF LIVE SATELLITES PER STATION
      DO 124 I=1,nsite
      DO 124 J=1,nsat
 124  IF(PHI(I,J).EQ.0.D0) ISTATC(I)=ISTATC(I)-1
C
CD     WRITE(6,200) (ISATC(I),I=1,nsat)
CD     WRITE(6,201) (ISTATC(I),I=1,nsite)
CD  200 FORMAT(' ISATC =',6I5)
CD  201 FORMAT(' ISTATC =',6I5)
C
C SQUEEZE ZERO COLUMNS (NO SATELLITES) OUT OF ISATC ARRAY
C ISATX IS THE SQUEEZED ARRAY
C ISAT IS THE NUMBER OF LIVE SATELLITES (IN PAIRS, AT LEAST)
      ISAT=0
      DO 5 J=1,nsat
       ISATX(J)=0
       IF(ISATC(J).EQ.0) GO TO 5
       ISAT=ISAT+1
       ISATX(ISAT)=ISATC(J)
C RECORD GOOD COLUMNS (SATELLITES)
       JSATX(ISAT)=J
   5  CONTINUE
C
CD     WRITE(6,21) (JSATX(II),II=1,ISAT)
CD   21 FORMAT(' JSATX : ',6I5)
C RECORD GOOD ROWS (STATIONS)
C  NUMBER OF LIVE STATIONS
      ISTAT=0
      DO 6 I=1,nsite
      IF(ISTATC(I).EQ.0) GO TO 6
      ISTAT=ISTAT+1
   6  CONTINUE
C
C     ARE THERE ANY OBSERVATIONS THIS EPOCH
      IOBS=0
      IF(ISTAT.GT.1) GO TO 25
      GO TO 99
C
   25 CONTINUE
C
C FILL BETWEEN STATION OPERATOR AND SQUEEZE ARRAYS
C  COUNTER FOR NUMBER OF ONEWAY PHASES USED
      ICNT=0
C  LOOP BY SATELLITE (COLUMN)
      DO 30 J=1,ISAT
      JND=JSATX(J)
CD     WRITE(6,23) J,JND
CD   23 FORMAT(' J,JND :',2I5)
C  FIND FIRST STATION (FIRST GOOD ROW)
      DO 31 I=1,nsite
      IF(PHI(I,JND).EQ.0.D0) GO TO 31
      IROW1=I
      IROW2=IROW1
      GO TO 32
   31 CONTINUE
   32 CONTINUE
C COUNT NUMBER OF ELEMENTS BEFORE FIRST GOOD ROW
      IELEM1=0
      IF(IROW1.EQ.1) GO TO 34
      DO 33 IJ=1,IROW1-1
      IELEM1=IELEM1+ISTATC(IJ)
   33 CONTINUE
   34 CONTINUE
CD     WRITE(6,100) IROW1,IELEM1
CD  100 FORMAT(' IROW1,IELEM1 =',2I5)
C
C  J LOOPS UP TO THE NUMBER OF SINGLE-DIFFERENCES
      DO 40 K=1,ISATX(J)-1
C  NUMBER OF TOTAL SINGLE-DIFFERENCES
      IOBS=IOBS+1
C  FIND NEXT STATION (RELATIVE TO FIRST GOOD ROW)
      DO 41 II=IROW2+1,nsite
      IF(PHI(II,JND).EQ.0.D0) GO TO 41
      ITEMP=II
      GO TO 42
   41 CONTINUE
   42 IROW2=ITEMP
C NUMBER OF ELEMENTS BEFORE CURRENT ROW
      IELEM2=0
      DO 43 III=1,IROW2-1
      IELEM2=IELEM2+ISTATC(III)
   43 CONTINUE
CD     WRITE(6,101) IROW2,IELEM2
CD  101 FORMAT(' IROW2,IELEM2 =',2I5)
C
C DETERMINE STATUS OF SATELLITE IN ROWS IROW1 AND IROW
      ICOL1=0
      DO 45 JJ=1,J
      IND1=JSATX(JJ)
      IF(PHI(IROW1,IND1).EQ.0.D0) GO TO 45
      ICOL1=ICOL1+1
   45 CONTINUE
      ICOL2=0
      DO 46 JJ=1,J
      IND2=JSATX(JJ)
      IF(PHI(IROW2,IND2).EQ.0.D0) GO TO 46
      ICOL2=ICOL2+1
   46 CONTINUE
CD     WRITE(6,500) ICOL1,ICOL2
CD  500 FORMAT(' ICOL1,ICOL2 =',2I5)
C  TWO ELEMENTS PER ROW OF SINGLE-DIFFERENCE OPERATOR
C  ELEMENTS ARE ALTERNATING -1 AND 1
      DO 50 L=1,2
      ICNT=ICNT+1
      GO TO (60,70) L
   60 D(ICNT)=-1.D0
      IPNTD(ICNT)=IELEM1+ICOL1
      GO TO 50
   70 D(ICNT)=1.D0
      IPNTD(ICNT)=IELEM2+ICOL2
   50 CONTINUE
C
C RECORD STATION AND SATELLITE USED
C
CD      WRITE(6,987) IROW1,IROW2,JND
CD  987 FORMAT(' STATION',I3,' STATION',I3,' SATELLITE',I3)
      IUSE(IROW1,JND)=IUSE(IROW1,JND)+1
      IUSE(IROW2,JND)=IUSE(IROW2,JND)+1
C BACKUP IN THE CASE DOUBLE IS NOT CALLED (OPERATOR DOESN'T CHANGE)
      IUSEBK(IROW1,JND)=IUSEBK(IROW2,JND)+1
      IUSEBK(IROW1,JND)=IUSEBK(IROW2,JND)+1
C
   40 CONTINUE
C      DONG FORGOT WHAT HE WAS DOING....
C      ICOL=ICOL+ISATX(I)
   30 CONTINUE
C
      IROWD(2)=0
      ICNT=0
      DO 90 I=1,IOBS
       ICNT=ICNT+2
       IROWD(I+2)=ICNT
   90 CONTINUE
      IROWD(1)=ICNT
C
   99 CONTINUE
C
CD     WRITE(6,300) (D(I),I=1,2*IOBS)
CD     WRITE(16,300) (D(I),I=1,2*IOBS)
CD  300 FORMAT(12F5.0)
CD     WRITE(6,301) (IPNTD(I),I=1,2*IOBS)
CD     WRITE(16,301) (IPNTD(I),I=1,2*IOBS)
CD  301 FORMAT(12I5)
CD     WRITE(6,301) (IROWD(I),I=1,IOBS+2)
CD     WRITE(16,301) (IROWD(I),I=1,IOBS+2)
CD      WRITE(6,400) ISTAT,ISAT,IOBS
CD      WRITE(16,400) ISTAT,ISAT,IOBS
CD400  FORMAT(' NUMBER OF STATIONS :',I3/
CD    1     ' NUMBER OF SATELLITES :',I3/
CD    2     ' NUMBER OF BETWEEN STATIONS OBSERVATIONS :',I3)
C
      RETURN
      END
