Copyright (c) Massachusetts Institute of Technology,1986. All rights reserved.
C
      REAL*8 FUNCTION DEGRED(STRDUM)
C
C DECODE THE STRING.IF THE STRING CONTAINS NO ':' THE INPUT IS
C  DECIMAL DEGREES. OTHERWISE IT IS DEG:MIN:SEC
C  RETURNS RADIANS
C
      implicit none

      integer*4 ielem2,ic,mm,ideg,ic1,imin,ielem1,iform1,ic2,iform2,m

      real*8 radian,sec

      CHARACTER*1 STRING(20)
      CHARACTER*4 CHARS2
      CHARACTER*6 CHARS1
      CHARACTER*2 BUF2
      CHARACTER*3 BUF3
      CHARACTER*9 BUF9
      CHARACTER*20 STR,STRDUM
C
      EQUIVALENCE (STRING,STR)
C
      DATA RADIAN/57.29577951308232D0/
C
      DATA CHARS2,CHARS1/'(A )','(F . )'/
C----------------------------------
C
c     initialization to avoid compiler warning
      ielem2 = 0

CD     WRITE(6,3294) STRDUM
CD 3294 FORMAT(1X,A20)
C
C RIGHT JUSTIFY STRING
      CALL RJUST(20,STRDUM)
      STR=STRDUM
CD     WRITE(6,3294) STR
C
      M=INDEX(STR,':')
      IF(M.GT.0) GO TO 100
C ANGLE IN DECIMAL DEGREES
      READ(UNIT=STR,FMT='(D20.16)') DEGRED
C
      GO TO 1000
C
C ANGLE IN DEGREES, MINUTES, SECONDS
100   CONTINUE
C
C REMOVE NUMBER OF PARENTHESIS
C CHECK FOR MINUS SIGN AND SAVE
      MM=INDEX(STR,'-')
      IF(MM.GT.0) STRING(MM)=' '
C
C LOCATE FIRST COLON
      IC=INDEX(STR,':')
CD     WRITE(6,*) IC
C BLANK FIRST COLON
      STRING(IC)=' '
C PICK OUT UP TO THREE DIGITS FOR DEGREES
      WRITE(UNIT=BUF3,FMT='(A3)') STR(IC-3:IC-1)
      READ(UNIT=BUF3,FMT='(I3)') IDEG
C LOOK FOR REMAINING COLON
      IC1=INDEX(STR,':')
C PICK OUT UP TO TWO DIGITS FOR MINUTES
      WRITE(UNIT=BUF2,FMT='(A2)') STR(IC1-2:IC1-1)
      READ(UNIT=BUF2,FMT='(I2)') IMIN
C DETERMINE NUMBER OF ELEMENTS IN SECONDS FIELD
      IELEM1=20-IC1
C COMPUTE ASCII VALUE OF SECONDS FIELD
      IFORM1=IELEM1+48
C CONVERT TO CHARACTER
      CHARS1(3:3)=CHAR(IFORM1)
C FIND DECIMAL POINT IF ANY
      IC2=INDEX(STR,'.')
      IF(IC2.EQ.0) GO TO 150
      IELEM2=20-IC2
CD     WRITE(6,*) IC2,IELEM2
C FIND ASCII VALUE OF NUMBER OF DECIMALS TO RIGHT OF DECIMAL POINT
      IFORM2=IELEM2+48
C CONVERT TO CHARACTER
      CHARS1(5:5)=CHAR(IFORM2)
      GO TO 151
  150 CHARS1(5:5)='0'
  151 CONTINUE
C SET UP A-FORMAT
      CHARS2(3:3)=CHARS1(3:3)
C PICK OUT CHARACTERS FOR SECONDS
CD     WRITE(6,22) CHARS1,CHARS2
CD   22 FORMAT(1X,A6,1X,A4)
      WRITE(UNIT=BUF9,FMT=CHARS2) STR(IC1+1:IC1+IELEM2)
      READ(UNIT=BUF9,FMT=CHARS1) SEC
C
C COMPUTE DECIMAL DEGREES
      DEGRED=SEC/3600.D0+DBLE(IMIN)/60.D0+DBLE(IDEG)
CD     WRITE(6,25) IDEG,IMIN,SEC
CD   25 FORMAT(1X,I4,1X,I2,1X,F5.1)
C REPLACE MINUS SIGN
      IF(MM.GT.0) DEGRED=-DEGRED
C
1000  CONTINUE
C
      DEGRED=DEGRED/RADIAN
C
      RETURN
      END
