      SUBROUTINE STDBLE(IPOS,ISCOL,IPOS1,IPOS2,ISAT,IS1,IS2)
C
C DETERMINE STATIONS AND SATELLITES THAT FORM A DOUBLE DIFFERENCE
C
      include '../includes/dimpar.h'
      DIMENSION IPOS(MAXOBS),ISCOL(MAXSAT)
C
C  POSITION TO START OF COLUMN IN IPOS
C  ISAT1 DENOTES COLUMN
C  IPOS1 AND IPOS2 - POSITIONS IN COLUMN
C
      IPT=0
      DO 10 I=1,ISAT
      IPT=IPT+ISCOL(I)
   10 CONTINUE
C BACKUP TO START OF ROW
      IPT=IPT-ISCOL(ISAT)
      IS1=IPOS(IPT+IPOS1)
      IS2=IPOS(IPT+IPOS2)
C
      RETURN
      END
