#!/bin/csh -f
# Script test speed
if( $#argv > 0 ) then
    set N = $1
else
    set N = 500
endif

set host = `hostname | awk -F . '{print $1}'`
set progs = `echo benchd  benchd.141108  benchd.caputo  benchd.newprey`
set it = 20
set f = "BENCHD.speed"
touch $f
echo "`date`: Run $host" >> $f
uptime >> $f
set n = 0
foreach p ( $progs )
   @ n++
   echo `date +"%Y%d%m:%H%M"` Starting $p
   set all = " 0.0 0.00"
   foreach j (`seq 1 $it`)
      set avs = `$p $N | grep '^   ..\.....  ' | awk '{s = s + $4} END {printf(" %9.2f",s/NR)}'`
      echo `date +"%Y%d%m:%H%M"` $host $j $N $p $avs | awk '{printf("%s %-10s %3d %5d %-15s %s\n",$1,$2,$3,$4,$5,$6)}' >> $f
      set all = `echo $all $avs | awk '{printf("%12.2f %f",$1+$3, $2+$3^2)}'` 
   end
   set avs = `echo $all $it | awk '{printf("%9.2f",$1/$3)}'` 
   set sig = `echo $all $it | awk '{printf("%6.2f",sqrt((($2-($1/$3)^2*$3)/$3)/$3))}'`
   echo `date +"%Y%d%m:%H%M"` $host $n $it $N $p $avs $sig | awk '{printf("%s %-10s %3d %3d %5d %-15s %s +- %-6s AVERAGE\n",$1,$2,$3,$4,$5,$6,$7,$8)}' >> $f
   uptime >> $f
   echo " " >> $f
end
echo "-----------------------------------------------------------------" >> $f

